- libs/feature-workspaces/src/lib/new-workspace/new-workspace.component.ts
Resolves https://github.com/nrwl/angular-console/issues/97
> fix(create-workspace): Disable closing terminal dialog while running

- apps/angular-console/src/app/app.module.ts
Hi guys,
thanks for using Apollo! :) I refactored a bit the way you initialize Apollo. There's a InjectionToken for it so it all runs on DI level.
I've got a tons of new features for you and I'm going to push it one by one, starting soon.
> Use APOLLO_OPTIONS

- package-scripts.js
- package.json
> fix: scripts section gets removed from package.json

- libs/feature-workspaces/src/lib/new-workspace/new-workspace.component.html
- libs/feature-workspaces/src/lib/new-workspace/new-workspace.component.ts
- libs/schema/src/index.ts
- libs/utils/src/lib/finder.service.ts
- server/src/api/read-directory.ts
- server/src/graphql-types.ts
- server/src/schema/resolvers.ts
- server/src/schema/type-defs.ts
- yarn.lock
This reverts commit 34e9ac5d60ba0233be42aef7b06a9faa63aaa59f.
> fix: validation on workspace name to prevent conflicts

- libs/utils/src/lib/command-runner.service.ts
- package.json
- server/src/api/commands.ts
- server/src/api/detailed-status-calculator.ts
- server/src/api/run-command.ts
- server/src/graphql-types.ts
- server/src/schema/resolvers.ts
- server/src/schema/type-defs.ts
- server/test/api/commands.spec.ts
- server/test/api/detailed-status-calculator.spec.ts
- yarn.lock
Detailed status is used to render the UI, in addition to the terminal
> feat: add detailed status for build and serve

- server/src/api/read-extensions.ts
Added my favorite prettier schematic that works to add prettier into angular project.
> feat: add a prettier schematic

- apps/angular-console-e2e/src/integration/forms.spec.ts
- apps/angular-console-e2e/src/integration/utils.ts
- libs/ui/src/lib/flags/flags.component.html
- libs/ui/src/lib/flags/flags.component.scss
Co-authored-by: Wassim Chegham <github@wassim.app>
> feat(ui-flags): Use angular material rounded inputs for flags.

- package-scripts.js
- package.json
- yarn.lock
- Changes electron build config so that server/assets is included.
- Fixed a typo in package-scripts.js
> fix: Fixed scripts so that `yarn startdev.prepare` work

- package.json
Reverts nrwl/angular-console#372
> Revert "chore(deps): update dependency @angular-devkit/core to v7"

- libs/ui/src/lib/task-selector/task-selector.component.ts
task selector filters on the description as well as name. Improving extension searching.
Original commit author @domisginger (https://github.com/nrwl/angular-console/pull/280)
Closes #188
> feat: improved filtering on task search bar

- server/src/api/read-extensions.ts
Adds link for @ionic/angular and description to available extensions
> feat: add @ionic/angular to list of extensions

- server/src/api/read-extensions.ts
Add the angular-fire-schematics extension.
> Add AngularFire Schematics

- libs/feature-extensions/src/lib/extensions/extensions.component.ts
- libs/ui/src/lib/task-selector/task-selector.component.html
The extensions screen makes it clear to see which extensions are installed.
> feat: make it easier to see what extensions are installed

- README.md
This add the mono-repo book banner to the readme file.
> chore(readme): add monorepo book banner

- apps/vscode/src/app/pseudo-terminal.factory.ts
> fix(vscode): Do not add commands to bash history

- apps/angular-console-e2e/src/integration/extensions.spec.ts
- apps/angular-console-e2e/src/integration/forms.spec.ts
- apps/angular-console-e2e/src/integration/generate-workspace-schematics.spec.ts
- apps/angular-console-e2e/src/integration/generate.spec.ts
- apps/angular-console-e2e/src/integration/no_node_modules.spec.ts
- apps/angular-console-e2e/src/integration/projects.spec.ts
- apps/angular-console-e2e/src/integration/tasks.spec.ts
- apps/angular-console-e2e/src/integration/tasks.utils.ts
- apps/angular-console-e2e/src/integration/utils.ts
- libs/feature-generate/src/lib/schematics/schematics.component.ts
Using `cy.contains('.title', 'My Title')` instead of `cy.get('.title').contains('My Title')`.
And `cy.get('.something', { timeout: 5000 } )` instead of `cy.wait(5000); cy.get('.something');`
> test: Clean up cypress tests

- angular.json
- apps/angular-console/src/styles.scss
- apps/vscode/src/app/tree-item/workspace-route.ts
- apps/vscode/src/app/tree-view/current-workspace-tree-provider.ts
- apps/vscode/src/app/webview.factory.ts
- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- apps/vscode/tsconfig.json
Removes CSS transform which made fonts blurry on windows
> fix(vscode): Remove recent/favorite trees and smooth fonts

- README.md
Update the Readme's banner for the connect event.
> chore(readme): banner update for connect event

- libs/server/src/lib/utils/file-utils.ts
> fix(server): use cmd and exe executables only on windows

- libs/ui/src/lib/build-status/build-status.component.ts
- libs/ui/src/lib/modules-graph/modules-graph.component.html
- libs/ui/src/lib/modules-graph/modules-graph.component.scss
- libs/ui/src/lib/modules-graph/modules-graph.component.ts
Also adds colours to apps and libs + styling tweaks.
> fix: Handle Windows paths when building webpack viz.

- README.md
> chore(readme): add book banner back

- apps/angular-console-e2e/src/integration/extensions.spec.ts
- libs/server/src/lib/api/read-extensions.ts
Closes https://github.com/nrwl/angular-console/issues/579
> feat(extensions): Integrate intellij's list of ng-add extensions

- .stylelintrc
- apps/angular-console/src/styles.scss
- libs/feature-action-bar/src/lib/action-bar.component.scss
- libs/feature-extensions/src/lib/extensions/extensions.component.ts
- libs/feature-generate/src/lib/schematics/schematics.component.ts
- libs/feature-install-node-js/src/lib/install-node-js.component.scss
- libs/feature-run/src/lib/targets/targets.component.ts
- libs/feature-workspaces/src/lib/new-workspace/new-workspace.component.scss
- libs/feature-workspaces/src/lib/projects/projects.component.scss
- libs/feature-workspaces/src/lib/workspace/workspace.component.scss
- libs/feature-workspaces/src/lib/workspaces/workspaces.component.scss
- libs/ui/src/lib/build-status/build-status.component.scss
- libs/ui/src/lib/command-output/command-output.component.scss
- libs/ui/src/lib/flags/flags.component.scss
- libs/ui/src/lib/task-runner/task-runner.component.scss
- libs/ui/src/lib/task-selector/task-selector.component.scss
- libs/ui/src/lib/test-status/test-status.component.scss
- libs/ui/src/lib/variables.scss
- package-scripts.js
- package.json
- yarn.lock
I started down the path of extracting all of our colors to a single file when I I got stuck and started adding a linter instead. The linter needs to be the thing that enforces that all colors need to go in one file
> feat(lint): Add style lint for scss linting

- apps/angular-console-e2e/src/integration/projects.spec.ts
- apps/angular-console/src/styles.scss
- libs/feature-workspaces/src/lib/graphql/workspace.graphql
- libs/feature-workspaces/src/lib/projects/projects.component.html
- libs/feature-workspaces/src/lib/projects/projects.component.scss
- libs/feature-workspaces/src/lib/projects/projects.component.ts
- libs/server/src/lib/api/install-nodejs.ts
- libs/server/src/lib/resolvers/mutation.resolver.ts
- libs/server/src/lib/resolvers/query.resolver.ts
Additionally, now buttons automatically hide/show based on the width of the window
> feat(projects): Show architect commands and filterable gen schematics

- README.md
Update the readme file with the Nrw Connect Platform banner.
> chore(readme): add connect banner

- README.md
Update the Nrwl Connect Platform banner.
> chore(readme): update connect banner

- apps/intellij/build.gradle
- apps/intellij/src/java/io/nrwl/ide/console/NgConsoleAppLifecycle.java
- apps/intellij/src/java/io/nrwl/ide/console/NgWorkspaceMonitor.java
- apps/intellij/src/java/io/nrwl/ide/console/server/RPCHandlerListener.java
- apps/intellij/src/java/io/nrwl/ide/console/ui/NgConsoleUI.java
Make sure to not register toolWindow while IDE indexing is in progress
> fix(intellij): Added DumbService to delay ToolWindow registration

- libs/server/src/lib/api/read-extensions.ts
Update devextreme-schematics package in extension list
> feat: update devextreme-schematics package in extension list

- libs/vscode-ui/components/src/lib/checkbox/checkbox.component.scss
- libs/vscode-ui/components/src/lib/field/field.component.html
- libs/vscode-ui/components/src/lib/field/field.component.scss
- libs/vscode-ui/components/src/lib/input/input.component.html
- libs/vscode-ui/components/src/lib/input/input.component.scss
- libs/vscode-ui/components/src/lib/select/select.component.html
- libs/vscode-ui/components/src/lib/select/select.component.scss
- libs/vscode-ui/styles/src/lib/_variables.scss
Fixed up basic VS code control styles
> style(vscode): form controls

- apps/vscode-ui/src/environments/environment.ts
- apps/vscode/src/app/angular-json-tree/angular-json-tree-item.ts
- libs/vscode-ui/components/src/lib/checkbox/checkbox.component.html
- libs/vscode-ui/components/src/lib/checkbox/checkbox.component.scss
- libs/vscode-ui/components/src/lib/field/field.component.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
Support for configurations
Support for properly setting default values
Checkboxes allow for toggling via clicking description
> fix(vscode-ui): Various fixes

- apps/vscode/src/app/ng-task/ng-task-provider.ts
- apps/vscode/src/app/start-server.ts
- apps/vscode/src/app/telemetry.ts
- apps/vscode/src/app/vscode-storage.ts
- apps/vscode/src/app/webview.ts
- apps/vscode/src/package.json
- libs/vscode-ui/components/src/lib/field-tree/field-tree.component.scss
- libs/vscode-ui/components/src/lib/field/field.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
- libs/vscode-ui/styles/src/lib/_variables.scss
- package-scripts.js
feat(vscode): Add analytics for opening the UI/executing a task
fix(vscode-ui): Set appropriate theme colors for buttons/tabs/active
> feat(vscode): Add analytics for opening the UI/executing a task

- apps/vscode-ui/src/environments/environment.ts
- libs/vscode-ui/components/src/index.ts
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.html
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.scss
- libs/vscode-ui/components/src/lib/checkbox/checkbox.component.html
- libs/vscode-ui/components/src/lib/checkbox/checkbox.component.scss
- libs/vscode-ui/components/src/lib/field-tree/field-tree.component.html
- libs/vscode-ui/components/src/lib/field-tree/field-tree.component.ts
- libs/vscode-ui/components/src/lib/field/field.component.html
- libs/vscode-ui/components/src/lib/field/field.component.scss
- libs/vscode-ui/components/src/lib/input/input.component.html
- libs/vscode-ui/components/src/lib/input/input.component.scss
- libs/vscode-ui/components/src/lib/select/select.component.html
- libs/vscode-ui/components/src/lib/select/select.component.scss
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
- libs/vscode-ui/styles/src/lib/_variables.scss
feat(vscode-ui): Modified field indicator
ux(vscode-ui): Move run button to top and reset scroll when -c changed
> feat(vscode-ui): Modified field indicator, move run button to top

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
And disable interactivity for dry runs
> fix(vscode-ui): Only run dry run when form is valid

- angular.json
- apps/vscode/src/app/ng-task/ng-task-provider.ts
- apps/vscode/src/app/output-channel.ts
- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- libs/server/src/index.ts
- libs/server/src/lib/utils/utils.ts
- package.json
- yarn.lock
Place feedback in output channel rather than debug console
Telemetry for invalid angular.json parsing / node_modules caching
Error messaging for angular.json missing
Error message for node_modules missing
Place readme.md in root of packaged extension so that is appers in market place
> fix(error-handling): Give more feedback for common errors

- apps/vscode/src/app/ng-task/ng-task.ts
Fixes https://github.com/nrwl/angular-console/issues/883
> fix(vscode): Allow for multiple tasks of same type

- libs/server/src/lib/utils/utils.spec.ts
- libs/server/src/lib/utils/utils.ts
> fix(vscode): fix ordering for positional arguments for Generate feature

- apps/vscode/src/app/ng-task/ng-task-commands.ts
- apps/vscode/src/app/ng-task/ng-task-flag-quick-pick-item.ts
- apps/vscode/src/app/ng-task/select-flags.ts
- apps/vscode/src/app/verify-workspace/verify-builder-definition.ts
- apps/vscode/src/app/webview.ts
- apps/vscode/src/app/workspace-tree/get-task-execution-schema.ts
- libs/schema/src/index.ts
- libs/server/src/lib/utils/read-projects.ts
- libs/server/src/lib/utils/read-schematic-collections.ts
- libs/server/src/lib/utils/utils.spec.ts
- libs/server/src/lib/utils/utils.ts
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.ts
- libs/vscode-ui/components/src/lib/checkbox/checkbox.component.ts
- libs/vscode-ui/components/src/lib/field-tree/field-tree.component.ts
- libs/vscode-ui/components/src/lib/field/field.component.ts
- libs/vscode-ui/components/src/lib/input/input.component.ts
- libs/vscode-ui/components/src/lib/select/select.component.ts
- libs/vscode-ui/feature-task-execution-form/src/index.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.schema.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/vscode-ui-feature-task-execution-form.module.ts
Rename Schema interface to Option (exported from angular CLI)
Remove many utility methods that are not called
> chore: Code cleanliness

- apps/vscode/src/app/ng-task/nx-task.ts
- apps/vscode/src/app/select-schematic.ts
- apps/vscode/src/app/webview.ts
- libs/server/src/index.ts
- libs/server/src/lib/utils/read-schematic-collections.ts
- libs/server/src/lib/utils/utils.ts
Fixes https://github.com/nrwl/angular-console/issues/895
> fix(vscode): Execute workspace schematics correctly

- apps/vscode/src/app/ng-task/shell-execution.ts
Fixes https://github.com/nrwl/angular-console/issues/898
> fix(vscode): Use path to derive path to bash

- apps/vscode/src/app/ng-task/ng-task-commands.ts
- apps/vscode/src/app/verify-workspace/verify-builder-definition.ts
Fixes https://github.com/nrwl/angular-console/issues/918
> fix(vscode): prompt for configuration flag

- apps/vscode/src/package.json
- libs/vscode-ui/components/src/lib/field/field.component.ts
> Fix project field

- apps/vscode/src/app/verify-workspace/verify-workspace.ts
- libs/server/src/index.ts
- libs/server/src/lib/utils/read-projects.ts
- libs/server/src/lib/utils/read-schematic-collections.ts
- libs/server/src/lib/utils/utils.ts
converts workspace, package.json, generators, and executors to Legacy formats to support Nx11
> convert to legacy format to support Nx 11

- apps/vscode/src/package.json
- libs/server/src/lib/utils/utils.spec.ts
- libs/server/src/lib/utils/utils.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
Fixes the field type to be Select or Autocomplete for properties with long form x-prompts items
> Fixes field type for long form x-prompt properties

- apps/vscode/src/app/workspace-tree/get-task-execution-schema.ts
- apps/vscode/src/package.json
- libs/server/src/lib/utils/utils.ts
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.html
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.scss
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.ts
- libs/vscode-ui/components/src/lib/field/field.component.html
- libs/vscode-ui/components/src/lib/field/field.component.scss
- libs/vscode-ui/components/src/lib/field/field.component.ts
- libs/vscode-ui/components/src/lib/input/input.component.html
- libs/vscode-ui/components/src/lib/input/input.component.scss
- libs/vscode-ui/components/src/lib/input/input.component.ts
- libs/vscode-ui/components/src/lib/multiple-select/multiple-select.component.html
- libs/vscode-ui/components/src/lib/multiple-select/multiple-select.component.scss
- libs/vscode-ui/components/src/lib/multiple-select/multiple-select.component.ts
- libs/vscode-ui/components/src/lib/select/select.component.html
- libs/vscode-ui/components/src/lib/select/select.component.scss
- libs/vscode-ui/components/src/lib/select/select.component.spec.ts
- libs/vscode-ui/components/src/lib/select/select.component.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.spec.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
- libs/vscode-ui/styles/src/lib/_variables.scss
* Fixes project entries dropdown
* Makes x-prompt properties without a default required
* Shows form validation errors and disables Run if invalid
* Run all commands with --no-interactive, not just the dryRun
> validates form input and run command with --no-interactive

- nx.json
- package.json
- yarn.lock
> add nx-cloud

- angular.json
- jest.config.js
- libs/vscode-ui/components/jest.config.js
- libs/vscode-ui/components/src/lib/multiple-select/multiple-select.component.html
- libs/vscode-ui/components/src/lib/multiple-select/multiple-select.component.spec.ts
- libs/vscode-ui/components/src/lib/multiple-select/multiple-select.component.ts
- libs/vscode-ui/components/src/lib/select/select.component.html
- libs/vscode-ui/components/src/lib/select/select.component.spec.ts
- libs/vscode-ui/components/src/lib/select/select.component.ts
- libs/vscode-ui/feature-task-execution-form/jest.config.js
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.spec.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
> fix: unit tests on vscode-ui libs

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
small change to only do the dryRun runCommand for Generate if the form is valid
> feat: only execute dry run if Generate form is valid

- angular.json
- apps/vscode-ui/src/environments/environment.ts
- apps/vscode-ui/webpack.dev.js
- libs/server/.eslintrc.json
- libs/vscode-ui/components/tsconfig.lib.json
- libs/vscode-ui/feature-task-execution-form/tsconfig.lib.json
- libs/vscode-ui/styles/tsconfig.lib.json
- libs/vscode/webview/src/lib/webview.ts
- package-scripts.js
- package.json
- yarn.lock
This change allows for better debugging with the webview in the extension. Summary of changes:
* inline source maps for better breakpoints
* when the main.js file changes, the webview html will be re-rendererd
> chore: better debugging for webview (ng app)

- libs/vscode/webview/src/lib/get-task-execution-schema.ts
Remove any leading `/` after replacing all `\` with `/`
Fixes #1061 assuming it's an OS path issue
> fix: replace \ with / in path in workspace before remove leading /

- libs/vscode/webview/src/lib/get-task-execution-schema.ts
* Loads the workspace defaults into the Run executor form
* Supports the configuration tab in the Run form when targets have one or more configurations
> feat: load workspace defaults into Run executor form

- .vscode/launch.json
- libs/vscode/json-schema/src/lib/workspace-json-schema.ts
This includes adding json schema for the `configuration` portion of the workspace file. Also includes descriptions for specific properties.
> feat: add json schema support for configurations, and also provide descriptions

- .github/workflows/ci_checks.yml
- .github/workflows/pr_title.yml
- .github/workflows/publish.yml
- Updated github actions to their latest versions
- Cache the Yarn Cache Directory instead of node_modules
- Removed Matrix from Publish workflow
> ci(github): updated actions

- package.json
- yarn.lock
Removed unused dependencies: 
- @ngrx/component-store
- babel-loader
- fast-glob
- tsickle
> chore(deps): removed unused deps

- libs/server/src/lib/utils/read-schematic-collections.ts
Support the update in json schema for `$id`
https://json-schema.org/understanding-json-schema/structuring.html#id
https://github.com/nrwl/nx/issues/5655#issuecomment-841135635
> fix: json schema update for $id

- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
Also makes sure that the fallback is used properly
Fixes #1144
> fix: use proper file schema for importing on windows

- libs/server/src/index.ts
- libs/server/src/lib/utils/build-project-path.ts
- libs/server/src/lib/utils/read-collections.ts
- libs/vscode/nx-workspace/src/lib/find-workspace-json-target.ts
- libs/vscode/nx-workspace/src/lib/reveal-workspace-json.ts
- libs/vscode/nx-workspace/src/lib/workspace-codelens-provider.ts
Provides a codelens to go to a project.json file from the main workspace.json file.
> feat: Go to project.json file from workspace file with codelens

- package-scripts.js
- package.json
- tools/scripts/postinstall.js
- tools/scripts/vscode-vsce.js
- tools/scripts/vscode-yarn.js
> chore: restore package creation utils :sweat_smile:

- libs/server/src/lib/utils/read-projects.ts
- libs/vscode/nx-workspace/src/lib/verify-workspace.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
Uses the correct workspace path for the generate command.
Fixes #1198
> fix: use proper workspace path to load generators

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
Makes sure that arguments are unique while using the UI form. 
fixes #1247
> fix: make sure that arguments are unique for the UI form

- apps/vscode/src/main.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-config.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
- libs/vscode/nx-workspace/src/lib/nx-version.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
> fix: check if projectGraph is out of sync

- apps/vscode/project.json
> fix: package external extension dependencies

- apps/vscode/src/commands/refresh-workspace.ts
- apps/vscode/src/main.ts
- libs/vscode/nx-workspace/src/lib/nx-workspace.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
> fix: optimize file watches

- libs/vscode/nx-workspace/src/lib/get-nx-workspace-config.ts
> fix: do not include workspace deps in project view

- libs/schema/src/index.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
> fix: x-dropdown options populate projects properly

- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- libs/vscode/nx-help-and-feedback-view/.eslintrc.json
- libs/vscode/nx-help-and-feedback-view/README.md
- libs/vscode/nx-help-and-feedback-view/jest.config.ts
- libs/vscode/nx-help-and-feedback-view/package.json
- libs/vscode/nx-help-and-feedback-view/project.json
- libs/vscode/nx-help-and-feedback-view/src/index.ts
- libs/vscode/nx-help-and-feedback-view/src/lib/nx-help-and-feedback-provider.ts
- libs/vscode/nx-help-and-feedback-view/src/lib/nx-help-and-feedback-tree-item.ts
- libs/vscode/nx-help-and-feedback-view/tsconfig.json
- libs/vscode/nx-help-and-feedback-view/tsconfig.lib.json
- libs/vscode/nx-help-and-feedback-view/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
We want to make it easier for users to access relevant help and information as well as encourage them to provide feedback.
A new view with links to docs & github is introduced.
> feat: add help & feedback view

- apps/vscode/src/package.json
- libs/vscode/project-graph/src/lib/graph-webview.ts
- libs/vscode/project-graph/src/lib/graph.machine.typegen.ts
- libs/vscode/project-graph/src/lib/project-graph.ts
* make focus and select project items only show in nx  workspaces
* add telemetry for executing graph actions.
> fix: always start the graph service on graph commands

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
> fix: add argument flags for positional arguments greater than 0

- apps/vscode/src/main.ts
- libs/vscode/nx-workspace/src/index.ts
- libs/vscode/nx-workspace/src/lib/stop-daemon.ts
> fix: stop daemon on extension deactivation

- .gitignore
- apps/vscode-e2e/.eslintrc.json
- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- libs/vscode/configuration/src/lib/configuration-keys.ts
- libs/vscode/configuration/src/lib/global-configuration-store.ts
- libs/vscode/nx-commands-view/src/index.ts
- libs/vscode/nx-commands-view/src/lib/init-nx-commands-view.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-provider.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-tree-item.ts
> feat: configurable common commands

- apps/vscode/src/package.json
- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
> feat: add context menu to execute task without Nx cache

- libs/vscode/project-graph/src/lib/create-project-graph.ts
- libs/vscode/project-graph/src/lib/graph-webview.ts
- libs/vscode/project-graph/src/lib/graph.machine.spec.ts
- libs/vscode/project-graph/src/lib/graph.machine.ts
- libs/vscode/project-graph/src/lib/graph.machine.typegen.ts
- libs/vscode/project-graph/src/lib/load-html.ts
example:
the error will still be displayed in the output console
> feat: display error result if creating graph fails

- LICENSE
> chore: updated LICENSE year

- apps/vscode/src/package.json
the current one doesn't really say anything
> chore: update extension description

- libs/vscode/nx-cloud-view/src/lib/auth/nx-cloud-authentication-provider.ts
- libs/vscode/nx-cloud-view/src/lib/nx-cloud-service/nx-cloud-api.service.ts
- libs/vscode/nx-cloud-view/src/lib/nx-cloud-service/nx-cloud-service.ts
https://github.com/nrwl/nx-console/issues/1473
> fix: remove nx cloud authentication badge

- libs/language-server/workspace/src/lib/read-collections.ts
See: https://github.com/nrwl/nx/pull/14561
> feat: hide deprecated generators and executors

- apps/intellij/build.gradle.kts
- apps/intellij/src/main/kotlin/dev/nx/console/MyBundle.kt
- apps/intellij/src/main/kotlin/dev/nx/console/ProjectPostStartup.kt
- apps/intellij/src/main/kotlin/dev/nx/console/completion/NxCompletionContributor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/completion/createLookupItem.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/CustomResourceHandler.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/CustomSchemeHandlerFactory.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/NxGenerateUiAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/Messages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/NxGenerateUiFileEditor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/NxGenerateUiFileEditorProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/utils/GetHexColor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/utils/OnBrowserLoad.kt
- apps/intellij/src/main/kotlin/dev/nx/console/listeners/NxEditorListener.kt
- apps/intellij/src/main/kotlin/dev/nx/console/listeners/ProjectManagerListener.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsProcess.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/client/NxlsLanguageClient.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/managers/DocumentManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxGeneratorOptionsRequest.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxGeneratorsRequest.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxlsLanguageServer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/MyProjectService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/ApplicationUtils.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/DocumentUtils.kt
- apps/intellij/src/test/kotlin/dev/nx/console/MyPluginTest.kt
- build.gradle.kts
Formatting can be done with `./gradlew :apps:intellij:ktfmtFormat` or via ktfmt plugin https://plugins.jetbrains.com/plugin/14912-ktfmt
> chore(intellij): add formatting support via ktfmt

- apps/vscode/project.json
- libs/vscode/nx-cloud-view/project.json
- tools/scripts/copy-cloud-webview-deps.mjs
fixes a regression from https://github.com/nrwl/nx-console/pull/1494
> fix: correctly copy nxls files to vscode dist when building

- apps/intellij/project.json
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxGeneratorOptionsRequest.kt
- libs/generate-ui/feature-task-execution-form/src/lib/ide-communication/ide-communication.service.ts
- libs/generate-ui/feature-task-execution-form/src/lib/task-execution-form/task-execution-form.component.ts
note that we have to accomodate both gson & json for now...
> fix(intellij): serialize more generator option properties 

- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/NxGenerateUiAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/Messages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxGeneratorsRequest.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxGetGeneratorContextFromPathRequest.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
- apps/nxls/src/main.ts
- libs/language-server/types/src/index.ts
- libs/language-server/workspace/src/index.ts
- libs/language-server/workspace/src/lib/get-generator-context-from-path.ts
- libs/language-server/workspace/src/lib/get-project-by-path.ts
- libs/shared/schema/src/index.ts
- libs/shared/schema/src/is-project-option.ts
- libs/vscode/nx-workspace/src/index.ts
- libs/vscode/nx-workspace/src/lib/get-generator-context-from-path.ts
- libs/vscode/nx-workspace/src/lib/get-project-by-path.ts
- libs/vscode/nx-workspace/src/lib/workspace-codelens-provider.ts
- libs/vscode/project-graph/src/lib/project-graph.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
- refactor: move get project by path to nxls
- refactor: add get generator context from path to nxls
- feat: open generate ui with project right click
> feat(intellij): open generate ui with project right click

- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/Messages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/editor/NxGenerateUiFile.kt
- apps/intellij/src/main/resources/generate_ui/index.html
- libs/generate-ui/components/src/lib/checkbox/checkbox.component.html
- libs/generate-ui/components/src/lib/checkbox/checkbox.component.scss
- libs/generate-ui/components/src/lib/field-tree/field-tree.component.scss
- libs/generate-ui/components/src/lib/field/field.component.scss
- libs/generate-ui/feature-task-execution-form/src/lib/ide-communication/ide-communication.service.ts
- libs/generate-ui/feature-task-execution-form/src/lib/task-execution-form/task-execution-form.component.scss
- libs/generate-ui/styles/src/lib/intellij/_variables.scss
- libs/generate-ui/styles/src/lib/vscode/_variables.scss
- libs/shared/schema/src/task-execution-messages.ts
- libs/vscode/webview/src/lib/webview.ts
- refactor: change text color handling in generate ui
- fix: use installed intellij font for webview
> fix: update styles and fix style-related bugs in generate ui

- apps/vscode/src/package.json
- libs/vscode/tasks/src/lib/select-generator.ts
> feat: add wildcard support to generatorAllowlist and generatorBlocklist

- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/run_generator/NxGeneratorMessageFilter.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/run_generator/RunGeneratorManager.kt
This PR will provide links for created/updated files on console
> feat(intellij): provide file links for created/updated files

- libs/shared/schema/src/normalize-schema.ts
fixes https://github.com/nrwl/nx-console/issues/1538
two things:
- if there’s no x-priority, i.e. an old nx version, we fall back to the old sorting in order to not leave folks’ forms messy
- we also take positional args into account, so that name is first even thought there are other required options that are earlier  in the alphabet
> fix: make sure first positional args are in the right order & fallback to old sorting

- apps/intellij/src/main/kotlin/dev/nx/console/cli/NxCreateWorkspaceProjectGenerator.kt
- apps/intellij/src/main/kotlin/dev/nx/console/cli/NxNewProjectModuleBuilder.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
- apps/intellij/src/main/resources/messages/NxConsoleBundle.properties
This PR add nx create workspace generator
> feat(intellij): add nx create workspace project generator

- apps/intellij/src/main/kotlin/dev/nx/console/ProjectPostStartup.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/run_generator/RunGeneratorManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/settings/EnableDryRunOnGenerateChangeSetting.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/editor/NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsProcess.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/WorkspacePathSetting.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/requests/NxChangeWorkspaceNotification.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/settings/NxConsoleProjectSettingsProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/settings/NxConsoleSettingsConfigurable.kt
- apps/intellij/src/main/kotlin/dev/nx/console/settings/NxConsoleSettingsProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxBasePath.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
- move to settings folder
- register workspace path project setting
- rework setting rendering
- apply workspace path setting on startup
> feat(intellij): add setting to specify non-root nx workspace path

- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandConfiguration.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandConfigurationType.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationEditor.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
This PR will add first run configuration for nx tasks
> feat(intellij): add nx run configuration

- apps/intellij/src/main/kotlin/dev/nx/console/generate/run_generator/RunGeneratorManager.kt
this PR will fix the issue of showing console running indicator icon
> feat(intellij): show console running indicator

- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandConfiguration.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationEditor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationProducer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunLineMarkerContributor.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
This PR will add gutter icon to project.json files to run nx targets on projects
> feat(intellij): add nx run line marker contributor for project.json

- libs/generate-ui/components/src/lib/autocomplete/autocomplete.component.scss
- libs/generate-ui/components/src/lib/checkbox/checkbox.component.scss
- libs/generate-ui/components/src/lib/field-tree/field-tree.component.scss
- libs/generate-ui/components/src/lib/field/field.component.scss
- libs/generate-ui/feature-task-execution-form/src/lib/ide-communication/ide-communication.service.ts
- libs/generate-ui/feature-task-execution-form/src/lib/task-execution-form/task-execution-form.component.scss
- libs/generate-ui/styles/src/lib/intellij/_variables.scss
- libs/generate-ui/styles/src/lib/vscode/_variables.scss
- libs/shared/schema/src/task-execution-messages.ts
here's some screenshots showing the new font sizes
> chore(generate-ui): set font size via styling message

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGenerateService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGeneratorSearchEverywhereContributorFactory.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGeneratorSearchEvrywhereContributor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/actions/NxGenerateUiAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/NxGeneratorListCellRenderer.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
this PR will add nx generator search evrywhere contributor
> feat(intellij): add nx generator search evrywhere contributor

- .run/Run Plugin.run.xml
- apps/intellij/build.gradle.kts
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxToolWindow.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxRefreshWorkspaceAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsProcess.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/managers/DocumentManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/ui/Notifier.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
- apps/intellij/src/main/resources/messages/NxConsoleBundle.properties
- apps/nxls/project.json
This handles errors while trying to start the nxls if there are errors in the workspace. 
A notification will appear giving a explaination and a way to refresh the workspace after
Fixes #1617
> fix: handle nxls startup errors

- apps/intellij/src/main/kotlin/dev/nx/console/ProjectPostStartup.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGenerateService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/run_generator/RunGeneratorManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/GetNodeInterpreter.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxExecutable.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxGeneralCommandLine.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxlsWorkingPath.kt
Fixes running Nx Console within wsl on Intellij
fixes #1632
> feat(intellij): run with wsl

- README.md
> chore: update readme for information on how to configure wsl

- apps/vscode/package.json
- apps/vscode/src/main.ts
- libs/vscode/nx-run-target-view/src/lib/run-target-tree-provider.ts
Also changes the order in which the run targets tree view loads
fixes #1670
fixes #1660
> fix(vscode): show select workspace in non-workspaces

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsProcess.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- apps/nxls/project.json
- apps/nxls/src/main.ts
- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
> fix(nxls): support running under node 14

- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/models/NxGeneratorOption.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- libs/generate-ui/feature-task-execution-form/src/lib/ide-communication/ide-communication.service.ts
- libs/shared/schema/src/task-execution-messages.ts
> fix(generate-ui): handle multiple default values for generate ui

- libs/generate-ui/feature-task-execution-form/src/lib/task-execution-form/task-execution-form.component.ts
fixes https://github.com/nrwl/nx-console/issues/1540
> fix(generate-ui): correctly serialize options with array default values

- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
fixes https://github.com/nrwl/nx-console/issues/1648
> fix(vscode): use more robust project:target syntax for running tasks

- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
- libs/language-server/workspace/src/lib/get-nx-workspace-package.ts
> fix(nxls): handle the daemon output so that stdout isnt polluted

- apps/intellij/src/main/kotlin/dev/nx/console/graph/actions/NxGraphFocusTaskAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxProjectsTreeStructure.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxSimpleNode.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/actions/EditNxProjectConfigurationAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxProjectConfigurationPath.kt
- apps/intellij/src/main/resources/messages/NxConsoleBundle.properties
Adds the option to edit the project configuration via context menu in the tool window. Also has a the same short cut as editing source files (f4 by default)
Closes https://github.com/nrwl/nx-console/issues/1678
> feat(intellij): add edit project configuration to nx console tool window

- .vscode/launch.json
- apps/nxls/project.json
- apps/nxls/src/main.ts
- libs/language-server/capabilities/code-completion/src/lib/get-completion-items.spec.ts
- libs/language-server/capabilities/code-completion/src/lib/get-completion-items.ts
- libs/language-server/capabilities/code-completion/src/lib/path-completion.ts
- libs/language-server/capabilities/code-completion/src/lib/project-completion.ts
- libs/shared/json-schema/src/lib/common-json-schema.ts
- libs/shared/json-schema/src/lib/completion-type.ts
- libs/shared/json-schema/src/lib/nx-json-schema.ts
- libs/shared/json-schema/src/lib/package-json-schema.ts
- libs/shared/json-schema/src/lib/project-json-schema.ts
Adds support for the new `dependsOn` and `namedInputs` schema for nx16
> feat(nxls): update dependsOn and namedInputs completion for nx 16

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/managers/DocumentManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/providers/NxlsDocumentationProvider.kt
- apps/nxls/src/main.ts
- libs/language-server/capabilities/hover/.eslintrc.json
- libs/language-server/capabilities/hover/README.md
- libs/language-server/capabilities/hover/jest.config.ts
- libs/language-server/capabilities/hover/package.json
- libs/language-server/capabilities/hover/project.json
- libs/language-server/capabilities/hover/src/index.ts
- libs/language-server/capabilities/hover/src/lib/get-hover.spec.ts
- libs/language-server/capabilities/hover/src/lib/get-hover.ts
- libs/language-server/capabilities/hover/tsconfig.json
- libs/language-server/capabilities/hover/tsconfig.lib.json
- libs/language-server/capabilities/hover/tsconfig.spec.json
- tsconfig.base.json
- add hover to lsp & vscode
- add hover to intellij
> feat: add hover with links to nx.dev for executors

- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphContextMenuHandler.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphDownloadHandler.kt
This PR will allow download graph as png on button click and not show contextual menu on right button click.
> feat(intellij): allow nx graph download

- apps/intellij/src/main/kotlin/dev/nx/console/graph/actions/NxGraphSelectAllAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxToolWindow.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
> feat(intellij): add toolwindow button to view full project graph

- apps/intellij/src/main/kotlin/dev/nx/console/generate/run_generator/RunGeneratorManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/Messages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/NxGenerateUiFile.kt
> fix(intellij): correctly display & run workspace generators via the UI

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/actions/EditNxProjectConfigurationAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/ProjectJsonPSIUtils.kt
> feat(intellij): enable jumping to target & configuration from toolwindow

- libs/generate-ui/feature-task-execution-form/src/lib/task-execution-form/task-execution-form.component.ts
> fix(vscode): repair generate ui docs link

- apps/generate-ui-v2/src/components/button.ts
- apps/generate-ui-v2/src/components/field-list.ts
- apps/generate-ui-v2/src/components/field-nav-item.ts
- apps/generate-ui-v2/src/components/fields/mixins/checkbox-wrapper-mixin.ts
- apps/generate-ui-v2/src/components/fields/mixins/field-wrapper-mixin.ts
- apps/generate-ui-v2/src/ide-communication.controller.ts
- apps/generate-ui-v2/src/main.ts
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/GenerateUiMessages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/V2NxGenerateUiFile.kt
- libs/shared/generate-ui-types/src/lib/messages.ts
- libs/vscode/generate-ui-webview/src/lib/generate-ui-webview.ts
- feat: pass font size to jetbrains UI
- form width
- correctly pass font size to vscode
> fix: adjust font size and some spacing

- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
in hindsight it's a kind of funny logical mistake
fixes #1782
> fix(nxls): fix broken version comparison for file map

- libs/shared/npm/src/lib/npm-dependencies.ts
> fix: properly catch errors when reading package.json files

- apps/intellij/src/main/resources/icons/nx-console.svg
- apps/intellij/src/main/resources/icons/nx-console_dark.svg
refer to this youtrack for my source: https://youtrack.jetbrains.com/issue/IDEA-298083
fixes #1726
> fix(intellij): update icons to match spec - fixes wrong color when selected

- .prettierrc
- apps/generate-ui-v2/src/components/badge.ts
- apps/generate-ui-v2/src/components/banner.ts
- apps/generate-ui-v2/src/components/button.ts
- apps/generate-ui-v2/src/components/field-list.ts
- apps/generate-ui-v2/src/components/field-nav-item.ts
- apps/generate-ui-v2/src/components/fields/array-field.ts
- apps/generate-ui-v2/src/components/fields/checkbox-field.ts
- apps/generate-ui-v2/src/components/fields/input-field.ts
- apps/generate-ui-v2/src/components/fields/mixins/checkbox-wrapper-mixin.ts
- apps/generate-ui-v2/src/components/fields/mixins/field-wrapper-mixin.ts
- apps/generate-ui-v2/src/components/fields/multiselect-field.ts
- apps/generate-ui-v2/src/components/fields/select-field.ts
- apps/generate-ui-v2/src/components/search-bar.ts
- apps/generate-ui-v2/src/main.ts
- package.json
- yarn.lock
just to have some consistency in how things are ordered
> chore: sort tailwind classes with prettier

- apps/generate-ui-v2/project.json
- apps/generate-ui-v2/tailwind.config.js
we're just moving config around
> chore: specify content in tailwind.config.js for windows compat

- apps/intellij/build.gradle.kts
- apps/intellij/project.json
- apps/nxls/package.json
- apps/vscode/package.json
- gradle.properties
- package.json
- tools/scripts/vscode-yarn.js
- yarn.lock
fixes https://github.com/nrwl/nx-console/issues/1440
> fix: update @parcel/watcher for more prebuilt binaries

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
fixes https://github.com/nrwl/nx-console/issues/1773
> fix(intellij): handle nxls shutdown without blocking

- libs/vscode/nx-cli-quickpicks/src/lib/select-run-information.ts
fixes https://github.com/nrwl/nx-console/issues/1812
> fix(vscode): use target to determine real list of projects

- libs/language-server/watcher/src/lib/watcher.ts
this obviously isn't a magic fix, just a bandaid for now. 
fixes https://github.com/nrwl/nx-console/issues/1824
> fix(nxls): increase watcher debounce to avoid daemon timing issues

- apps/generate-ui-v2/src/main.ts
> fix(generate-ui): add hover tooltip to copy button

- apps/generate-ui-v2/src/ide-communication.controller.ts
- apps/generate-ui-v2/src/tailwind.css
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/GenerateUiMessages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/V2NxGenerateUiFile.kt
- apps/intellij/src/main/resources/generate_ui_v2/index.html
- libs/shared/generate-ui-types/src/lib/messages.ts
> fix: make scrollbar look more native in intellij

- apps/generate-ui-v2-e2e/src/e2e/field-list.cy.ts
- apps/generate-ui-v2/src/components/field-list.ts
- apps/generate-ui-v2/src/components/field-nav-item.ts
- apps/generate-ui-v2/src/components/show-more-divider.ts
some behavior changes to make navigation easier also refactoring to make the code more readable (kinda messy before)
> fix(generate-ui): refactor field list & show greyed out hidden options

- apps/vscode/package.json
- libs/vscode/generate-ui-webview/src/lib/generate-commands.ts
- libs/vscode/generate-ui-webview/src/lib/init-generate-ui-webview.ts
> feat(vscode): add generate/move/remove to project view context menu

- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphBrowser.kt
- apps/vscode/package.json
- libs/vscode/nx-workspace/src/lib/get-nx-workspace.ts
- libs/vscode/project-graph/src/lib/graph-webview.ts
- libs/vscode/project-graph/src/lib/load-html.ts
corresponding nx PR: https://github.com/nrwl/nx/pull/18315
also added some telemetry
> feat: enable opening project configuration files & running tasks from graph

- apps/vscode/src/main.ts
- libs/language-server/types/src/index.ts
- libs/vscode/lsp-client/src/lib/configure-lsp-client.ts
- libs/vscode/nx-conversion/src/lib/vscode-nx-conversion.ts
- libs/vscode/project-graph/src/lib/graph-webview.ts
- tsconfig.base.json
fixes https://github.com/nrwl/nx-console/issues/1845 and does some refactoring
> fix(vscode): don't register vscode things twice & remove outdated stuff from main.ts

- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/V2NxGenerateUiFile.kt
> fix(intellij): register schema handler after the cefBrowser is created

- libs/language-server/watcher/src/lib/watcher.ts
Fixes https://github.com/nrwl/nx/issues/18703
> fix(nxls): use ignore globs from nx for the file watcher

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxToolWindowPanel.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/tree/NxTreeStructure.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandConfiguration.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxTaskExecutionManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/actions/NxRunAnythingAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/getOrCreateRunnerAndConfigurationSettings.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
enables debug mode for nx run configurations. Adds it to multiple places: 
- Gutter Actions in project.json
- Nx Toolwindow 
- Nx: Run Anything action
fixes https://github.com/nrwl/nx-console/issues/1868
Todo:
> feat(intellij): add debug mode to run configurations 

- libs/vscode/nx-cli-quickpicks/src/lib/select-run-information.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
> fix(vscode): fix configuration codelens running the correct config

- apps/intellij/src/main/kotlin/dev/nx/console/ProjectPostStartup.kt
this PR makes sure the nxls is only started for nx workspaces, similar to how vscode does it.
The nxls shouldn't be active in non-nx workspaces and it was sometimes causing issues there. 
fixes https://github.com/nrwl/nx-console/issues/1896
tested on macos & windows
> fix(intellij): scan for nx workspace before starting nxls

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/tree/NxTreeStructure.kt
hopefully fixes https://github.com/nrwl/nx-console/issues/1876
> fix(intellij): reload tree model on main thread

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/requests/NxCreateProjectGraphRequest.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
the schema change (passing showAffected to nxls) broke intellij serialization. that's fixed.
> fix(intellij): make sure affected feature doesnt break intellij graph

- libs/shared/nx-console-plugins/src/lib/internal-plugins/name-and-directory.plugin.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/project-name-and-root-plugin.ts
fixes https://github.com/nrwl/nx-console/issues/1942
> fix(nxls): take default options into account when prefilling as-provided options

- apps/generate-ui-v2/src/components/show-more-divider.ts
fixes https://github.com/nrwl/nx-console/issues/1940
> fix(generate-ui): show fewer options instead of show less options

- libs/vscode/nx-config-decoration/src/lib/reveal-nx-project.ts
- libs/vscode/project-details/src/lib/init-vscode-project-details.ts
- libs/vscode/project-details/src/lib/project-details-manager.ts
- libs/vscode/project-details/src/lib/project-details-preview.ts
needs to have https://github.com/nrwl/nx/pull/21189 in a released1 17.3 beta or it will break because the api doesn't exist yet.
> feat(vscode): open pdv at target

- apps/nxls/src/main.ts
- libs/language-server/capabilities/code-completion/src/index.ts
- libs/language-server/capabilities/code-completion/src/lib/schema-completion.ts
- libs/language-server/workspace/src/lib/get-project-by-path.ts
- libs/shared/json-schema/src/index.ts
- libs/shared/json-schema/src/lib/project-json-schema.ts
- move schema to other file
- fix(nxls): enable target autocomplete for pcv3 projects
> fix(nxls): enable target autocomplete for pcv3 projects

- apps/vscode/src/main.ts
- libs/vscode/lsp-client/src/lib/configure-lsp-client.ts
- libs/vscode/utils/src/lib/watch-file.ts
fixes https://github.com/nrwl/nx-console/issues/1995
> fix(vscode): sendRequest error on startup

- apps/nxls/src/main.ts
- libs/language-server/types/src/index.ts
- libs/language-server/workspace/src/lib/get-nx-version.ts
- libs/language-server/workspace/src/lib/get-project-by-path.ts
- libs/language-server/workspace/src/lib/get-source-map.ts
- libs/vscode/nx-config-decoration/src/lib/reveal-nx-project.ts
- libs/vscode/nx-workspace/src/lib/get-project-by-path.ts
- libs/vscode/nx-workspace/src/lib/get-source-map.ts
- libs/vscode/project-details/src/lib/config-file-codelens-provider.ts
- libs/vscode/project-details/src/lib/init-vscode-project-details.ts
- libs/vscode/project-details/src/lib/project-details-manager.ts
> feat(vscode): show codelenses in config files that create targets

- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
When calling the Nx daemon for the project graph, we initially had it reset the connection so that we don't leave the daemon in an open state. This caused an issue when trying to call the daemon again to get more information. Because the daemon client was reset after the first call, the second call failed because the "Daemon closed the connection". 
Now, we dont reset the client after getting the project, but manually reset after we get all required information from the daemon.
fixes #2005
> fix: reset daemon client after all daemon requests are completed only

- apps/vscode/package.json
- apps/vscode/src/main.ts
- libs/vscode/add-dependency/src/lib/add-dependency-codelens-provider.ts
- libs/vscode/configuration/src/lib/configuration-keys.ts
- libs/vscode/nx-config-decoration/src/lib/init-config-decoration.ts
- libs/vscode/nx-config-decoration/src/lib/workspace-codelens-provider.ts
- libs/vscode/project-details/src/lib/config-file-codelens-provider.ts
- libs/vscode/project-details/src/lib/project-details-codelens-provider.ts
- libs/vscode/utils/src/index.ts
- libs/vscode/utils/src/lib/register-codelens.ts
This fixes/updates the code lens setting in VSCode to enable/disable all codelens provided by nx console.
> feat(vscode): add all codelens to a settings toggle

- libs/language-server/workspace/src/lib/get-project-by-path.ts
Signed-off-by: Max Kless <maxk@nrwl.io>
> fix(nxls): handle windows paths better when getting project by path

- apps/nxls-e2e/src/completion/nx-json-plugin-inference.test.ts
- apps/nxls-e2e/src/utils.ts
- apps/nxls/src/main.ts
- libs/language-server/capabilities/code-completion/src/index.ts
- libs/language-server/capabilities/code-completion/src/lib/get-completion-items.ts
- libs/language-server/capabilities/code-completion/src/lib/inference-plugins-completion.ts
- libs/language-server/watcher/src/lib/watcher.ts
- libs/shared/json-schema/src/lib/completion-type.ts
- libs/shared/json-schema/src/lib/nx-json-schema.ts
- add inference plugin completion kind
- revert watcher change
- add plugin inference autocomplete tests
> feat: add autocomplete to nx.json plugins 

- libs/shared/utils/src/lib/get-nx-execution-command.ts
- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
fix https://github.com/nrwl/nx-console/issues/2057
> fix: remove -W and --silent flag for yarn

- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxExecutable.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxGeneralCommandLine.kt
fixes https://github.com/nrwl/nx-console/issues/2017
> fix(intellij): get correct executable path under yarn pnp

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGenerateService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/NxGraphStates.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/OldNxGraphBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/models/NxTreeMap.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/tree/NxTreeStructure.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxRefreshWorkspaceAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsDocumentationProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/requests/NxProjectsByPathsRequest.kt
- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectDetailsFileType.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandConfigurationType.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationProducer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/getOrCreateRunnerAndConfigurationSettings.kt
- apps/intellij/src/main/kotlin/dev/nx/console/settings/NxConsoleProjectSettingsProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/telemetry/TelemetryService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/jcef/CustomResourceHandler.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
fixes https://github.com/nrwl/nx-console/issues/2088
> refactor(intellij): specify action update thread & fix misc inspections

- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
fixes https://github.com/nrwl/nx-console/issues/2118
> fix(vscode): fix add dependency to show nx packages

- libs/vscode/nx-cli-quickpicks/src/lib/select-affected-flags.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-provider.ts
- libs/vscode/tasks/src/lib/cli-task-definition.ts
- libs/vscode/tasks/src/lib/cli-task-provider.ts
- libs/vscode/tasks/src/lib/cli-task.ts
fixes https://github.com/nrwl/nx-console/issues/2126
> fix(vscode): adapt cli task logic to handle affected & other commands correctly

- libs/vscode/nx-cli-quickpicks/src/lib/select-flags.ts
fixes https://github.com/nrwl/nx-console/issues/2107
> fix(vscode): enable command quickpicks to specify arbitrary options

- libs/language-server/workspace/src/lib/read-collections.ts
> fix(nxls): resolve delegated executor defintions correctly

- README.md
> chore: add JetBrains plugin version shield in readme

- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/NxGeneratorListCellRenderer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/file/NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/file/V2NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/models/NxGenerator.kt
fixes https://github.com/nrwl/nx-console/issues/1903#issuecomment-2161722107
> fix(intellij): handle undefined generator description

- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxExecutable.kt
fixes https://github.com/nrwl/nx-console/issues/2159
> fix(intellij): check that ./nx is not a folder before assuming it as binary

- apps/vscode/package.json
- libs/vscode/generate-ui-webview/src/lib/generate-commands.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-provider.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-tree-item.ts
Modifies 'Common Nx Commands' so that the "Generate (UI)" command is the default being run
> feat(vscode): make generate ui default in sidebar

- apps/intellij/src/main/kotlin/dev/nx/console/graph/NxGraphBrowserBase.kt
- apps/intellij/src/main/kotlin/dev/nx/console/models/NxCloudStatus.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectDetailsBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/actions/NxConnectAction.kt
- apps/nxls-e2e/src/nx-cloud/nx-cloud-16.test.ts
- apps/nxls-e2e/src/nx-cloud/nx-cloud-default.test.ts
- apps/nxls/src/main.ts
- apps/vscode/package.json
- apps/vscode/src/main.ts
- apps/vscode/src/nx-init.ts
- libs/language-server/types/src/index.ts
- libs/language-server/workspace/src/index.ts
- libs/language-server/workspace/src/lib/get-nx-cloud-status.ts
- libs/vscode/graph-base/src/lib/handle-graph-interaction-event.ts
- libs/vscode/nx-cloud-view/.eslintrc.json
- libs/vscode/nx-cloud-view/README.md
- libs/vscode/nx-cloud-view/jest.config.ts
- libs/vscode/nx-cloud-view/package.json
- libs/vscode/nx-cloud-view/project.json
- libs/vscode/nx-cloud-view/src/index.ts
- libs/vscode/nx-cloud-view/src/lib/init-nx-cloud-view.ts
- libs/vscode/nx-cloud-view/tsconfig.json
- libs/vscode/nx-cloud-view/tsconfig.lib.json
- libs/vscode/nx-cloud-view/tsconfig.spec.json
- libs/vscode/nx-workspace/src/index.ts
- libs/vscode/nx-workspace/src/lib/get-nx-cloud-status.ts
- tsconfig.base.json
- feat: add nx cloud view to vscode & nx connect action to both
- add nx console handler for nx connect
> feat: add nx connect action & vscode cloud pane

- libs/vscode/utils/src/lib/shell-execution.ts
Fixes https://github.com/nrwl/nx-console/issues/2138
> fix(vscode): escape quotes in windows powershell

- .env
- .gitignore
Co-authored-by: Craigory Coppola <craigorycoppola@gmail.com>
> chore(repo): enable plugin isolation

- apps/nxls-e2e/src/utils.ts
- nx.json
Plugin Isolation in nx 18 was enabled and causing issues.
thank you @leosvelperez
> fix: repair workspace-18 e2e & make sure .env is in sharedGlobals

- apps/vscode/package.json
- libs/vscode/nx-project-view/src/lib/atomizer-decorations.ts
- libs/vscode/nx-project-view/src/lib/init-nx-project-view.ts
- libs/vscode/nx-project-view/src/lib/nx-tree-item.ts
- libs/vscode/nx-project-view/src/lib/views/nx-project-base-view.ts
- feat(vscode): add decorations for atomized targets
- fix focus target action
> feat(vscode): add atomized target highlighting and info

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxReMoveProjectDialog.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/actions/NxReMoveProjectActions.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/tree/NxTreeStructure.kt
fixes https://github.com/nrwl/nx-console/issues/2170
> feat(intellij): make (re)move project actions available in toolwindow context menu

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxToolWindowPanel.kt
adds a warning text to the toolwindow with a button to change the setting & refresh the workspace.
fixes https://github.com/nrwl/nx-console/issues/2253
> fix(intellij): show better warning & help when no node interpreter is selected

- CONTRIBUTING.md
Add missing requirements to the CONTRIBUTING.md docs
> docs(contributing): update installation instructions

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsDocumentationProvider.kt
fixes an error reported by jetbrains exceptions
> fix(intellij): catch containingFile null error

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsProcess.kt
- libs/shared/npm/src/index.ts
- libs/shared/npm/src/lib/pnp-dependencies.ts
- libs/vscode/lsp-client/src/lib/nxls-client.ts
- fix(nxls): make sure nxls is spun up correctly in vscode & yarn pnp
- fix(intellij): enable nxls to work with yarn pnp
> fix: run nxls in a way that works with yarn pnp

- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
this is an oversight from a recent refactor
> fix(vscode): remove extra @ from add dependency logic

- apps/nxls/src/main.ts
- libs/vscode/lsp-client/src/lib/nxls-client.ts
- libs/vscode/nx-cloud-view/src/lib/cipe-notifications.spec.ts
- libs/vscode/nx-cloud-view/src/lib/cipe-notifications.ts
- libs/vscode/nx-cloud-view/src/lib/cloud-view-state-machine.ts
- libs/vscode/nx-cloud-view/src/lib/init-nx-cloud-view.ts
- **fix: remove nxls auto-shutdown**
- **remove sleep timer from state machine**
- **adjust notification implementation to not show notifs on first load**
> fix: disable nxls auto-shutdown & tweak cloud notifications

- apps/nxls/src/main.ts
- libs/language-server/utils/src/lib/nx-cloud.ts
- **handle misshaped nx.json error in cloud onboarding**
- **catch getDocumentLinks error and await returned promises**
> fix(nxls): handle broken nx.json better in nxls requests

- apps/vscode/package.json
- apps/vscode/project.json
- libs/vscode/copilot/src/lib/init-copilot.ts
- libs/vscode/copilot/src/lib/prompts/generate-prompt.tsx
- libs/vscode/copilot/src/lib/prompts/history.tsx
- libs/vscode/copilot/src/lib/prompts/nx-json-prompt.tsx
- libs/vscode/copilot/src/lib/prompts/project-graph-prompt.tsx
- libs/vscode/copilot/src/lib/prompts/prompt.tsx
- libs/vscode/copilot/src/lib/tools/generator-details-tool.ts
- libs/vscode/copilot/tsconfig.json
- libs/vscode/copilot/tsconfig.lib.json
- libs/vscode/utils/src/lib/shell-execution.ts
- **feat: add a more descriptive and readable project graph prompt**
- **adjust base, nx.json & generate prompts**
> fix(vscode): rework prompts

- libs/vscode/copilot/src/lib/init-copilot.ts
- libs/vscode/copilot/tsconfig.json
- libs/vscode/copilot/tsconfig.lib.json
- libs/vscode/telemetry/src/lib/telemetry-types.ts
- **feat: add a more descriptive and readable project graph prompt**
- **adjust base, nx.json & generate prompts**
- **fix pnpm bug, determine intent, adjust prompt**
- **tool to retrieve generator schemas**
- **generate prompt tweaking**
- **handle missing workspace data**
- **soften /generate requirements**
- **remove debug mode**
- **feat(vscode): add telemetry to ai interactions**
> feat(vscode): add telemetry to ai interactions

- libs/vscode/copilot/src/lib/context.ts
- libs/vscode/copilot/src/lib/init-copilot.ts
- libs/vscode/copilot/src/lib/prompts/docs-pages-prompt.tsx
- libs/vscode/copilot/src/lib/prompts/generate-prompt.tsx
- libs/vscode/copilot/src/lib/prompts/history.tsx
- libs/vscode/copilot/src/lib/prompts/prompt.tsx
- libs/vscode/copilot/tsconfig.json
- libs/vscode/copilot/tsconfig.lib.json
- **feat(vscode): add docs from nx-dev api to context**
- **tweaks**
> feat(vscode): feed docs into copilot integration (RAG)

- libs/language-server/workspace/src/lib/get-generators.ts
fixes https://github.com/nrwl/nx-console/issues/2411
> fix(nxls): repair generator reading with schematics/collection.json

- .github/workflows/ci_checks.yml
- libs/language-server/workspace/src/lib/nx-console-plugins.ts
- libs/shared/nx-console-plugins/src/index.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/index.ts
- libs/shared/nx-console-plugins/src/lib/nx-console-plugin-types.ts
- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
- libs/vscode/nx-project-view/src/lib/nx-tree-item.ts
- libs/vscode/nx-project-view/src/lib/views/nx-project-base-view.ts
- libs/vscode/nx-project-view/tsconfig.json
- libs/vscode/nx-project-view/tsconfig.lib.json
- **chore: WIP new projectViewItemProcessors plugin**
- **fix: init description in tree item**
- **chore: WIP new projectViewItemProcessors plugin (2)**
- **chore: WIP new projectViewItemProcessors plugin (3)**
- **chore: WIP new projectViewItemProcessors plugin (4)**
- **fix types**
- **add debuggin to CI**
> feat: new projectViewItemProcessors plugin

- apps/nx-mcp/README.md
Updates the instructions for configuring the nx-mcp server via the NPM package.
> docs(nx-mcp): update installation instructions

- README.md
updates README with VSCode MCP support
> chore(repo): update README to reflect VSCode MCP support

- libs/vscode/nx-cloud-view/src/cloud-onboarding-view.ts
we werent' passing the right parameters to the function imported from nx
> fix(vscode): repair finish setup in nx cloud action with nxCloudId set

- apps/intellij/build.gradle.kts
- apps/intellij/src/main/kotlin/dev/nx/console/ProjectPostStartup.kt
- apps/intellij/src/main/kotlin/dev/nx/console/mcp/McpServerService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/mcp/SetupMcpServerAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/Notifier.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
- **feat(intellij): add automatic mcp server configuration action**
- **show notification as well**
> feat(intellij): add automatic mcp server configuration action

- .github/workflows/claude.yml
- CLAUDE.md
inspired by angular-eslint and @JamesHenry, let's try working with claude
> chore(repo): add a claude github action via @claude

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/update-content.sh
- .gitignore
- apps/intellij/src/main/kotlin/dev/nx/console/cloud/CIPENotificationService.kt
- **chore(repo): add devcontainer setup for cursor background agents**
- **tweak devcontainer**
> chore(repo): create devcontainer setup for cursor background agents

- apps/intellij/build.gradle.kts
- apps/intellij/gradle.properties
- apps/intellij/src/main/kotlin/dev/nx/console/ProjectPostStartup.kt
- apps/intellij/src/main/kotlin/dev/nx/console/cloud/CIPENotificationService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/ide/project_json_inspection/AnalyzeNxConfigurationFilesAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/llm/FixCIPEService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/mcp/McpServerService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/Notifier.kt
- apps/intellij/src/main/resources/META-INF/nx-console-llm.xml
- apps/intellij/src/main/resources/META-INF/plugin.xml
- libs/intellij/models/build.gradle.kts
This ports the CI autofix action to intellij. It will provide an action to automatically open the AI assistant with a prompt prefilled if a task fails and the AI assistant & nx mcp are enabled.
> feat(intellij): enable fixing CI errors from notification

- apps/generate-ui-v2/tailwind.config.js
things broke during the refactor, we need to make sure that files from the lib are included in the tailwind content
> fix(generate-ui): fix tailwind after lib breakout

- libs/shared/types/src/lib/cloud-info.ts
- libs/vscode/nx-cloud-view/src/nx-cloud-fix-webview.ts
- Need to apply `NX_CONSOLE_INTELLIJ` value to https://github.com/nrwl/nx-console/pull/2604 or follow up
> feat: track ai fix action origin

- libs/shared/cloud-fix-webview/src/nx-cloud-fix-component.stories.ts
- libs/shared/cloud-fix-webview/src/nx-cloud-fix-component.ts
- libs/shared/ui-components/src/lib/components/icon.ts
some fixes for the ui:
- make icons bigger again across the status cards
- handle state better where an AI fix ran but didn't create any changes
> fix: self-healing UI improvements

- apps/intellij/src/main/kotlin/dev/nx/console/cloud/CIPENotificationService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/cloud/cloud_fix_ui/NxCloudFixFileImpl.kt
- apps/intellij/src/main/kotlin/dev/nx/console/telemetry/TelemetryTypes.kt
- libs/shared/telemetry/src/lib/telemetry-types.ts
- libs/vscode/nx-cloud-view/src/nx-cloud-fix-webview.ts
some events were missing in both editors
> fix: make AI telemetry more consistent

- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectConfigFilesService.kt
There's a deficiency in the IntelliJ apis where we can't asynchronously determine the type of editor to use for a certain file or refresh the kind later. In order to render the split editor in IntelliJ, we close and reopen the file to trigger this instead. 
The list of files that have PDV editors are cached locally between sessions so this happens rarely. 
But if you have a file open that doesn't have a PDV editor and then change the project graph in a way that means it should have a PDV editor, we have to resort to this.
> fix(intellij): prevent NPE while quickly closing/reopening files with PDV browser

- libs/vscode/nx-cloud-view/src/cipe-notifications.spec.ts
- libs/vscode/nx-cloud-view/src/cipe-notifications.ts
I made a mistake while implementing the new logic.
We should show a notification if a CIPE is re-checked during polling and nothing changed except for the 5 minute window for an AI fix to appear has passed.
We should NOT show this notification multiple times.
> fix(vscode): dont show CIPE notification multiple times even after ai fixes timed out

- apps/nxls/src/main.ts
- libs/language-server/watcher/src/lib/watcher.ts
- libs/shared/watcher/src/lib/native-watcher.ts
fixes https://github.com/nrwl/nx-console/issues/2337
We were still sending native watcher events after shutdown, which led to errors and hanging when restarting the nxls.
> fix(nxls): stop native watcher events from being sent after shutdown

- apps/vscode/package.json
- apps/vscode/src/main.ts
- apps/vscode/tsconfig.app.json
- apps/vscode/tsconfig.json
- libs/shared/telemetry/src/lib/telemetry-types.ts
- libs/shared/types/src/lib/cloud-info.ts
- libs/vscode/nx-cloud-view/src/apply-fix-locally.ts
- libs/vscode/nx-cloud-view/src/index.ts
- libs/vscode/nx-cloud-view/src/init-nx-cloud-view.ts
- libs/vscode/nx-cloud-view/src/nx-cloud-fix-webview.ts
- libs/vscode/nx-cloud-view/src/self-healing-uri-handler.ts
This pull request adds support for handling custom self-healing URIs in the Nx Console VSCode extension, enabling users to apply Nx Cloud fixes directly from deep links. It refactors how local fixes are applied and introduces new logic to find the correct workspace for a fix. Additionally, there are updates to TypeScript configuration files for proper library resolution and minor telemetry/type changes.
**Self-healing URI support and fix application:**
* Added a URI handler (`registerUriHandlers` in `apps/vscode/src/main.ts`) that listens for `onUri` activation events and processes self-healing URIs, allowing users to apply Nx Cloud fixes via deep links. (`[[1]](diffhunk://#diff-ffd752c4d60ebba40a59cc7f9b8cb7b3beeedb5c14a8a8245246bf73846bf247L42-R43)`, …
> feat(vscode): add uri handler for self healing links

- .github/workflows/ci_checks.yml
- .github/workflows/publish-nx-mcp.yml
- .mcp.json
- apps/nx-mcp/server.json
- apps/nx-mcp/setup-publish.js
refer to this guide https://github.com/modelcontextprotocol/registry/blob/main/docs/guides/publishing/publish-server.md
> chore(repo): set up publishing for nx-mcp to github registry

- apps/vscode/package.json
- libs/vscode/configuration/src/lib/configuration-keys.ts
- libs/vscode/mcp/src/lib/init-mcp.ts
- libs/vscode/mcp/src/lib/ports.ts
fixes https://github.com/nrwl/nx-console/issues/2785
> feat(vscode): allow MCP to run on fixed port via setting

- apps/intellij/src/main/kotlin/dev/nx/console/cloud/CIPENotificationService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/cloud/cloud_fix_ui/NxCloudFixFileImpl.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/GitUtils.kt
this is really useful to help folks stay up to date on their branch - vscode has it already
> feat(intellij): add button to fetch and pull changes after applying ai fix
