nrwl/nx-console

- README.md
Current behavior
Expected behavior
> docs: fix markdown parse

- electron/src/electron.ts
When closing the Electron app the window size and location is saved to the store and is used when opening the app to restore size and location.
Closes #92
> feat: add save/load of electron window size and location

- apps/angular-console-e2e/src/integration/workspaces.spec.ts
- apps/angular-console/src/app/app.component.ts
- apps/angular-console/src/index.html
The angular-console app will now update title accordingly. (closes #102)
- Title is now the breadcrumbs in reverse hierarchical order, with `Angular Console` appended at the end.
- The app component is responsible for syncing between breadcrumbs and document title.
> feat: syncs up breadcrumbs to document title

- package-scripts.js
Added `start-dev-server` script, as there isn't a good way (that I know of) to chain pass command line arguments from `nps`.
> build: add start-dev-server script that enables inspect for electron server

- package-scripts.js
- tools/scripts/test.js
Running `yarn start server.test` locally will run jest interactively with CPU count as max workers (default).
> chore: updates server test so jest can run interactively in non-CI environment

- libs/feature-workspaces/src/lib/new-workspace/new-workspace.component.html
remove the undesired behavior of the browser's autocomplete when creating a new workspace.
> fix: disable the browser's autocomplete when creating a new workspace

- CONTRIBUTING.md
It was missing from the CONTRIBUTING and people could think it was not possible
> docs: add script to run electron app on Linux

- apps/angular-console/src/app/app.component.html
- apps/angular-console/src/index.html
- libs/feature-action-bar/src/lib/action-bar.component.html
- libs/feature-extensions/src/lib/extension/extension.component.html
- libs/feature-extensions/src/lib/extensions/extensions.component.html
- libs/feature-generate/src/lib/schematic/schematic.component.html
- libs/feature-generate/src/lib/schematics/schematics.component.html
- libs/feature-install-node-js/src/lib/install-node-js.component.html
- libs/feature-run/src/lib/npmscript/npmscript.component.html
- libs/feature-run/src/lib/target/target.component.html
- libs/feature-run/src/lib/targets/targets.component.html
- libs/feature-settings/src/lib/settings/settings.component.html
- libs/feature-workspaces/src/lib/new-workspace/new-workspace.component.html
- libs/feature-workspaces/src/lib/projects/projects.component.html
- libs/feature-workspaces/src/lib/workspace/workspace.component.html
- libs/feature-workspaces/src/lib/workspaces/workspaces.component.html
- libs/ui/src/lib/build-status/build-status.component.html
- libs/ui/src/lib/command-output/command-output.component.html
- libs/ui/src/lib/contextual-action-bar/contextual-action-bar.component.html
- libs/ui/src/lib/data-collection/data-collection.component.html
- libs/ui/src/lib/flags/flags.component.html
- libs/ui/src/lib/task-runner/task-runner.component.html
- libs/ui/src/lib/task-selector/task-selector.component.html
- libs/ui/src/lib/terminal/terminal.component.html
- libs/ui/src/lib/test-status/test-status.component.html
- package-scripts.js
- package.json
- server/src/api/detailed-status-calculator.ts
- yarn.lock
> feat(formatting): Update prettier to 1.15

- apps/angular-console-e2e/src/integration/local-collection.spec.ts
- libs/feature-generate/src/lib/schematic/schematic.component.ts
- server/src/api/read-schematic-collections.ts
- tools/scripts/set-up-e2e-fixtures.js
check local package.json for the schematics attribute. when available add the path to the collection.
> feat: add local package.json to schematics collection

- package-scripts.js
Use 'withPlatform' in server.compile to gen Graphql with platform specific commands (copy vs cp)
#418
> fix: make graphql gen script platform specific

- libs/utils/src/lib/serializer.service.spec.ts
- libs/utils/src/lib/serializer.service.ts
Add 'required' check for determining important schematic fields
Add 'parentModule' for '@nrwl/schematics' auto completions
Add '@angular/cdk', '@angular/material' to standard completion handling
Fixes a typo in methodname reoderFields => reorderFields
#304
> fix: add new schematic collections for autocomplete and important fields

- server/src/api/read-extensions.ts
Add actual NgRx extension with schematics
Remove NgRx packages that don't
> fix: add missing '@ngrx/schematics' to extensions

- server/src/api/read-extensions.ts
@ngxs/schematics has been updated for compatibility with Angular console so adding to extension list
Closes #204
> feat: add ngxs schematics package to extension list

- apps/angular-console-e2e/src/integration/generate.spec.ts
- libs/server/src/lib/api/read-schematic-collections.spec.ts
- libs/server/src/lib/api/read-schematic-collections.ts
- libs/server/src/lib/utils.ts
- tools/scripts/set-up-e2e-fixtures.js
Fix for #156 .
This takes the approach of overriding the `defaultValue` when the schema is normalized.
Another possible solution would be to keep the existing `defaultValue` and add a `projectDefault`, so that the initial value is set to the `projectDefault`, but the `defaultValue` from the schema definition is still displayed in the description.
> fix: Use defaults from angular.json in generate form

- README.md
This PR fixes the Core Team table also I change the images inline-style to the reference-style to make it easier to maintain.
> fix(readme): Styling core team table.

- package.json
- yarn.lock
Automatically runs `yarn start format` before commits. This should prevent any failures during formatting checks in CI (unless you skip git hooks).
Also, the `frontend.format` was formatting server code (and tmp code from E2E tests) as well. I restricted the pattern to only `apps` and `libs`.
@mrmeku What do you think?
> chore: automatically format using prettier when commiting

- apps/angular-console-e2e/src/integration/projects.spec.ts
- apps/angular-console/src/app/app.component.ts
- libs/feature-extensions/src/lib/extensions/extensions.component.ts
- libs/feature-generate/src/lib/schematics/schematics.component.ts
- libs/feature-run/src/lib/targets/targets.component.ts
- libs/ui/src/lib/task-selector/task-selector.component.ts
- libs/utils/src/index.ts
- libs/utils/src/lib/router-navigation.service.spec.ts
- libs/utils/src/lib/router-navigation.service.ts
**Assumption:** There is always a location to go back to (which is true for this desktop app)
**Note:** There is a small delay in updating sidenav as seen below.
- Closes #435
> fix: Navigate back to previous location when active target or schematic is not present.

- apps/angular-console-e2e/src/integration/projects.spec.ts
- libs/feature-workspaces/src/lib/projects/projects.component.html
- libs/feature-workspaces/src/lib/projects/projects.component.ts
- libs/feature-workspaces/src/lib/workspace/workspace.component.ts
- libs/schema/src/lib/generated/graphql-types.ts
- libs/server/src/assets/schema.graphql
- libs/utils/src/lib/graphql/settings.graphql
- libs/utils/src/lib/graphql/update-settings.graphql
- libs/utils/src/lib/settings.service.spec.ts
- libs/utils/src/lib/settings.service.ts
Allow pinning on the projects page
1. When the component is loaded, the `pinnedProjectNames` are loaded from the settings service.  Any modifications are saved locally in the component and updated in settings.  Reloading the component will load the graphql settings version.  
**Alternative:**  I could make the settings service return an Observable of the workspace settings to avoid having any local component state.
2. I tried copying the `@growShrink` animation from the `workspaces` component, but that does not appear to play nicely with `<cdk-virtual-scroll-viewport>`
> feat: pinned projects

- libs/feature-settings/src/lib/settings/settings.component.scss
Simplified the css rules in the SettingsComponent and set default rules for .container.
Thus, there are margins and max-width even for screens larger than $largeScreen.
As a sideeffect, there are no longer separate rules needed for $largeScreen and $mediumScreen.
> fix: fixed margins in SettingsComponent on large screens (#445)

- apps/intellij/build.gradle
This make sure it does not include `Angular Console-X.X.X.zip `from `dist/apps/intellij `into the gradle build process `buildPlugin`.
> fix(intellij): exclude *.zip file from the buildPlugin process

- .vscode/launch.json
- CONTRIBUTING.md
- apps/angular-console/src/styles.scss
- package-scripts.js
Also implements `nps prepare.dev.vscode` to rebuild all vscode
dev artifcats more quickly than `nps prepare.vscode`
> fix(vscode): Set default font color to override vscode default

- libs/ui/src/lib/modules-graph/modules-graph.component.ts
The previous initial render was done in ngOnInit, which does not
guarantee that elements are available yet. It is now in ngAfterViewInit.
> fix: Bundle visualization renders correctly on initial render.

- libs/schema/src/index.ts
- libs/server/src/lib/api/detailed-status-calculator.spec.ts
- libs/server/src/lib/api/detailed-status-calculator.ts
- libs/server/src/lib/utils/stats.spec.ts
- libs/server/src/lib/utils/stats.ts
- libs/ui/src/lib/build-status/build-status.component.ts
Parse the stats only at the end (when `setStatus` is called). With differential loading, webpack produces two "done" output during build (es5, then es2015) so it's not a good place to check for assets generated.
> fix: Bundle visualization accounts for differential loading

- libs/ui/src/lib/task-selector/task-selector.component.scss
The last item is hidden below the fold and not accessible to
user.
Thanks!
> style: Change container height to show last task item

- libs/feature-run/src/lib/target/target.component.html
- libs/feature-run/src/lib/target/target.component.ts
The build command of a project applies default values from workspace configuration first. Fixes #605
> fix: Use build options from project workspace configuration

- apps/electron/src/app/pseudo-terminal.factory.ts
- libs/schema/src/lib/generated/graphql-types.ts
addresses issue #719
By setting the CI environment variable, we can ensure angular-cli always treats our terminal as non-interactive.
angular-cli checks for the analytics prompt here https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/analytics.ts#L387. That calls a tty checking function here https://github.com/angular/angular-cli/blob/master/packages/angular/cli/utilities/tty.ts#L21. I do not _think_ there are other implications to doing that, but this is potentially a quick fix.
> fix: Do not prompt for analytics

- apps/electron/src/app/start-server.ts
- apps/intellij/src/app/start-server.ts
- apps/vscode/src/app/start-server.ts
If you follow a trail of "this method is like that method", you end up here https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback. 
Relevant bit:
> If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.
resolves #797
> fix: only bind to localhost, not all interfaces

- libs/utils/src/lib/serializer.service.ts
Add support to override completion property from schema.json
Motivation: I've created custom schematics and want to use `projects` and `localModules` completion for my custom props
Example usage:
```
{
"$schema": "http://json-schema.org/schema",
"id": "new-component",
"type": "object",
"properties": {
"name": {
"type": "string",
"description": "Library name",
"$default": {
"$source": "argv",
"index": 0
}
},
"project": {
"type": "string",
"description": "Project",
"completion": "projects",
"$default": {
"$source": "projectName"
}
},
},
"required": [
"name"
]
}
```
> feat: Support providing `completion` property

- apps/electron/src/main.ts
this is due to conflict with default nest debugging port. angular console will use a random port if it conflicts, but nest does not. 
resolves #569
> feat: default nest port changed

- libs/server/src/lib/api/read-extensions.ts
fix: remove deprecated schematic
@briebug/jest was deprecated in favor of @briebug/jest-schematic
> fix: remove deprecated schematic

- apps/vscode/src/app/ng-task/ng-task-commands.ts
- apps/vscode/src/app/ng-task/ng-task-definition.ts
- apps/vscode/src/app/ng-task/ng-task-provider.ts
- apps/vscode/src/package.json
- angularConsole.generate.explorer is needed because we need a different title for the explorer menu
- changed selectNgCliCommandAndShowUi to prompt for a project if a project is not provided
> feat: add generate explorer menu command

- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.html
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.scss
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.ts
- libs/vscode-ui/components/src/lib/field/field.component.html
- libs/vscode-ui/components/src/lib/field/field.component.ts
- libs/vscode-ui/components/src/lib/input/input.component.html
- libs/vscode-ui/components/src/lib/select/select.component.html
- libs/vscode-ui/components/src/lib/vscode-ui-components.module.ts
Created autocomplete input component for VS Code
- The autocomplete component contains an input as well, which is different than most implementations. I can refactor it to attach to another component, now that the initial version is working.
- Zack suggested I use nested form controls instead of the current strategy I'm using in select, input, and checkbox, so I did that here. If this seems like a good configuration, I'll update the other inputs to use it too.
- I decided not to use the CDK overlay as it was causing some problems, but I do still have a version with it available if it should be used.
- I'm planning to work on tests next.
> feat(vscode): autocomplete

- apps/vscode/src/app/select-schematic.ts
- libs/server/src/lib/extensions.ts
- libs/vscode-ui/components/src/lib/autocomplete/autocomplete.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
- package-lock.json
add _ngx-semantic-version_ schematic which will add and configure commitlint, commitizen, husky and standard-version for creating commit messages in the conventional commit format and automate your release and Changelog generation respecting semver.
See also: https://www.npmjs.com/package/ngx-semantic-version
> chore: add ngx-semantic-version to extensions list

- libs/server/src/lib/extensions.ts
This will add [angular-cli-ghpages](https://github.com/angular-schule/angular-cli-ghpages) to the extensions list so that it will be installable as `ng add` package via Angular Console.
// CC @johanneshoppe
> chore: add angular-cli-ghpages as ng add extension

- apps/vscode-ui/src/environments/environment.ts
- apps/vscode/src/app/select-schematic.ts
- libs/server/src/lib/utils/read-schematic-collections.ts
- libs/vscode-ui/components/src/lib/select/select.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
Fixes parsing defaults from angular json
Fixes setting defaults from schematic fields (many were appearing as false)
Fixes setting default for select menus
> fix(vscode-ui): Correctly populate defaults

- apps/vscode/src/app/telemetry.ts
- libs/server/src/lib/telemetry/telemetry.ts
- Record "opt out" events before we stop collecting usage data.
- Reads from vscode configuration instead of our store since it doesn't appear we are updating the store anywhere.
> fix(vscode): fix opt-out event for data collection

- CONTRIBUTING.md
The CONTRIBUTING.md file had twice the section '**Building the VSCode plugin**'. I removed the section which had less info, and left the other one which has info related to Unit and e2e tests.
> fix: remove duplication from CONTRIBUTING.md

- apps/vscode/src/app/workspace-json-tree/workspace-json-tree-provider.ts
Load the projects pane after the other 2 side panel panes so that those side panels can be used right away in large workspaces.
Before:
After:
> feat: lazy load the projects pane

- libs/server/src/lib/utils/read-schematic-collections.ts
The generate command becomes unresponsive when there is an npm package with a `package.json` file that has a `schematics` property that does not point to a valid file.
This PR will skip the invalid `package.json` file instead of hanging.
> Handle missing schematics json file

- libs/vscode-ui/components/src/lib/input/input.component.scss
The insider's build of vscode changed the name of the input background css variable.
> fix input background color name

- apps/vscode/src/app/cli-task/cli-task-commands.ts
- apps/vscode/src/app/vscode-storage.ts
- apps/vscode/src/app/webview.ts
- apps/vscode/src/app/workspace-tree/get-task-execution-schema.ts
- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- libs/schema/src/index.ts
- libs/vscode-ui/components/src/lib/field/field.component.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
nx generate ui can be shown by right clicking in explorer context menu
the path you click on will be used as a value for the "path" option
the "project" option will also be updated based on the path 
See discussion in #974, issues listed there has been solved. 
I have only tested on windows so far. Should we make sure it works in mac and linux as well?
Any more changes or suggestions?
> feat: show generate ui from explorer context menu

- apps/vscode/src/app/select-schematic.ts
- libs/server/src/lib/utils/read-schematic-collections.ts
With Nx11, we need to also consider the tools/generators path when looking for schematic collections
> feat: consider the new workspace generators path

- apps/vscode/src/app/cli-task/cli-task-provider.ts
- apps/vscode/src/app/webview.ts
- libs/schema/src/index.ts
- libs/vscode-ui/components/src/lib/format-task/format-task.pipe.spec.ts
- libs/vscode-ui/components/src/lib/format-task/format-task.pipe.ts
- libs/vscode-ui/components/src/lib/vscode-ui-components.module.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
Dry runs on workspace generators/schematics were launching a new terminal window with each dry run when the user is filling out the properties.
* Updates the webview to pass through workspace generator/schematic commands to the CliTaskProvider which has support for deferred dry run
* Updates the Task Execution Form header to show the workspace generator/schematic command instead of `ng generate`
> Fixes opening new terminal on workspace generator dry run

- package-scripts.js
`ng build vscode-ui --watch --prod` generates runtime.js and main.js, which is what the [getIframHtml](https://github.com/nrwl/nx-console/blob/master/apps/vscode/src/app/webview.ts#L139) seems to expect; whereas,
`ng build vscode-ui --prod1` is generating runtime-es2015.js/runtime-es5.js and main-es2015.js/main-es5.js
Updates the package.vscode script to rename the files.
> temp fix to rename packaged -es2015.js files to .js

- .vscode/tasks.json
This sets the tasks.json to "listen" to the terminal output so that it can start up the next task. This means that we can start debugging with just F5 and not have to do weird workarounds.
> properly start debugging

- libs/schema/src/index.ts
- libs/server/src/lib/utils/utils.spec.ts
- libs/server/src/lib/utils/utils.ts
- libs/vscode-ui/components/src/lib/field/field.component.html
- libs/vscode-ui/components/src/lib/field/field.component.ts
- libs/vscode-ui/components/src/lib/multiple-select/multiple-select.component.spec.ts
- libs/vscode-ui/components/src/lib/select/select.component.spec.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.spec.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.stories.ts
- libs/vscode-ui/styles/src/lib/_variables.scss
* Fixes #1004 The Build form RUN_ONE_OPTIONS were not showing because those options didn't have the `component` property. I removed the `component` property that was recently added to TaskExecutionSchema Options in #986. The functionality to determine which component to show in the form belongs in the vscode-ui-components, so that's where I moved it.
* Actually, let's not disable the Run button when the Form is invalid. The Build form doesn't do a good job of populating workspace defaults on the project. Fields such as main and index are required in the schema, but these are configured and read from the workspace config.
* One run Generate commands with --no-interactive. (ng build was failing because it does not support the --no-interactive flag)
> Fix Build form RUN_ONE_OPTIONS checkboxes

- apps/vscode/src/app/workspace-tree/get-task-execution-schema.ts
Fixes #997 
It's not just the @nwrl/nest:controller generator. The directory property is also in @nrwl/node:application, @nrwl/node:library, and others.
> fix: support directory as path alias from context menu

- .versionrc.json
- angular.json
- package.json
- yarn.lock
Uses the `standard-version` tool to read commits and automatically bump versions and create git tags. 
This is done locally rather than a CI. Follow up PR to deploy the extension whenever a new version tag is pushed to the repo
> chore: create release tools to generate change log and bump verisons

- apps/vscode/src/package.json
- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
This change introduces a new button in the nx projects tree view that replaces the single click to open the workspace.json file. This allows us to focus the view and start typing so that we can use the built in filter in vscode. 
**Screenshots**:
New button to open workspace.json
Filter
Closes #1043
This is based off the current refactor branch, and will need to be rebased.
> feat: allow filtering in the nx project tree view

- apps/vscode/src/main.ts
- libs/vscode/nx-run-target-view/src/lib/run-target-tree-provider.ts
Loads the custom workspace path when the extension is loaded. This path is stored per vscode workspace. 
I also show a description of what the current workspace is:
Fixes: #965
> feat: load custom workspace path on extension load

- libs/vscode/webview/src/lib/get-task-execution-schema.ts
Fixes #1049 
The context menu path is taken from the full file system path with the workspace path parsed out of it, which was resulting in a leading space. Generator paths should always be relative to the workspace, so removing the leading `/`.
> fix: remove leading / from path parsed out of the workspace path

- .vscode/launch.json
- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- libs/server/src/index.ts
- libs/server/src/lib/utils/utils.ts
- libs/server/src/lib/utils/watch-file.ts
- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
Clicking the refresh icon in the Projects view will delete the cache for the current workspace file. 
This PR also adds a mechanism to watch the workspace file and automatically refresh the projects view. 
Closes #1042
> fix: refresh projects view clears cache

- libs/vscode/tasks/src/lib/nx-task-commands.ts
- libs/vscode/tasks/src/lib/select-flags.ts
* On the Nx: run-many command, when selecting projects it now prompts for selection from a quick pick list of projects with the given target instead of having the user type out the project entries.
* The target flag has also been included in the userSetFlags in order to show the target with the command being built up.
> feat: run-many prompts for projects

- apps/vscode/src/main.ts
- apps/vscode/src/package.json
With how the ["when" clause](https://code.visualstudio.com/api/references/when-clause-contexts) context for `isGenerateFromContextMenuEnabled` is just getting set on activate, this setting isn't applying immediately like other VS Code settings do. Seems like you have to reload the window to get the setting to work. 
But the "when" clause can read from the `config` settings in order to toggle it on/off in your current VS Code session, so this change should fix that.
> fix: enable generate from context menu setting take effect immediately

- apps/vscode/src/package.json
- libs/vscode/tasks/src/lib/cli-task-commands.ts
Adds support for `nx run` in the Command Palette
Prompts for a project then a target and supported flags (including configuration with a dropdown of the configuration options.)
> feat: nx run in command palette and context menu

- apps/vscode/src/package.json
fixes #992 task already active:
The tasks are keying off the properties in the taskDefinition, so adding the positional property makes `nx serve frontend` and `nx server api` different tasks. Same for ng tasks. This also works for flags, which were already in the taskDefinition, so `nx serve app` and `nx serve app --prod` are also different tasks.
> fix: add positional to taskDefinitions

- libs/schema/src/index.ts
- libs/server/src/lib/select-schematic.ts
- libs/server/src/lib/utils/read-schematic-collections.ts
Improves performance for `Generate` form and `nx generate` within command palette by only reading and normalizing options for the selected schematic.
Fixes: #925
> fix: only reads and normalizes selected schematic options

- apps/vscode/src/package.json
whoops! don't show those ng context menus for nx workspaces. I implemented the `ng.run` command in that last PR #1075 and added the menu, but I goofed and showed both sets of menus for Nx workspaces with angular.json.
> fix: don't show ng menus for nx workspaces

- libs/vscode/webview/src/lib/get-task-execution-schema.ts
I can't seem to figure out how we could determine if a schematic/generator is a project and what the projectType is from the schema before it is generated, and I am not totally happy with this `schematic.name === 'application' || schematic.name === 'app'` and `schematic.name === 'library' || schematic.name === 'lib'` solution. 
Update: added a commit that only sets project/projectName or path/directory from the explorer context menu, not both. Project takes precedence.
> fix: strip appsDir and libsDir from path if app|application or lib|library

- libs/vscode/json-schema/src/lib/get-all-executors.ts
Fixes the absolute path for the schema files for the workspace json schema. Windows should now have the proper absolute file 
path notation `file:///c:/.../schema.json` 
Fixes #1083
> fix: use proper file paths for schemas within windows

- package.json
- yarn.lock
`zlib` is a native Node.js module. nx-console should not depend on https://www.npmjs.com/package/zlib
> chore: remove dependency zlib

- apps/vscode/src/package.json
- libs/server/src/lib/utils/utils.ts
- package.json
- yarn.lock
- Updated `jsonc-parser` to 3.0.0
- Removed `strip-json-comments' from dependencies
- Removed `json5` from `apps/vscode/src/package.json`
- Replaced the `readAndParseJson` function by a faster implementation similar to the one at https://github.com/nrwl/nx/blob/4f429e0eab7f9294184166cef202688d434e21a8/packages/tao/src/utils/json.ts#L35
> refactor: removed json5 and strip-json-comments from dependencies and used jsonc-parser instead

- tools/scripts/postinstall.js
Removed obsolete vscode postinstall script: node ./node_modules/vscode/bin/install from tools/scripts/postinstall.js see: https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode
> chore(repo): remove obsolete vscode postinstall

- jest.preset.js
- libs/server/jest.config.js
- libs/server/src/lib/utils/utils.ts
- libs/server/src/test-setup.ts
- libs/server/tsconfig.spec.json
- libs/vscode/json-schema/src/lib/get-all-executors.ts
When creating the workspace.json schema, we now also read the package.json's dependencies object as well.
Also, I changed the `readAndParseJson` to output to the OutputChannel than throw errors. This should clean up some annoying popups for some users.
> fix: read package.json dependencies when getting builders/executors

- libs/server/src/lib/utils/read-schematic-collections.ts
Combines both schematics and generators schema's when reading schematics/generators
> fix: read and combine both schematics and generators

- libs/vscode/nx-workspace/src/lib/verify-workspace.ts
Add support for project.json split from angular.json too (Nx supports it for angular.json `version:2`)
> fix: support angular.json (v2) having split project.json files

- libs/vscode/tasks/src/lib/nx-task-commands.ts
adds the --watch option for `nx dep-graph` command. I noticed the `affected:dep-graph` doesn't support any of the dep-graph options, just the affected options, we may want to address that at some point as well.
> feat: support dep-graph watch option

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
Quick fix for an issue with autocomplete for generators with a short list of options with an autocomplete at the bottom.
Currently- autocomplete cut off at end of original height:
Fix- setting min-height of that container as well allows the autocomplete to expand:
Would be great to address #985 at some point as well, but this helps.
> fix: add min-height to scroll container so at least 100vh

- libs/vscode/tasks/src/lib/cli-task-provider.ts
Noticed that we were matching projects where the root is a partial match of another project, e.g. `/libs/my-lib-longer-name` was matched by `/libs/my-lib-long`
> fix: ensure project path is not just a partial match

- libs/vscode/webview/src/lib/get-task-execution-schema.ts
fixes #1086- if project  is found from context
I did some testing with different plugins, and I found there are inconsistencies on how `directory` is handled, but it is mostly relative to the project if a `project` option is also included. I added support for `directory` from the context menu uri within the past few months, and we didn't seem to notice these issues with the context path support before directory was added.
> fix: include path with project but not directory

- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
- libs/vscode/nx-workspace/src/lib/verify-workspace.ts
Loads the `@nrwl/workspace` file utils directly so that we don't require the main index file. When we require the main file, it'll try to load the `@angular/devkit` package. 
Fixes #1109
> fix: load workspace file utils directly

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
fixes #1116, I copy-pasta'ed the wrong min-height for has-configurations which was causing the Search bar and Run button to be hidden when using the side menu to scrollIntoView
> fix: menu scroll hides Run and Search bar header

- README.md
- angular.json
- apps/vscode/src/getting-started/1-generate.md
- apps/vscode/src/getting-started/2-run.md
- apps/vscode/src/getting-started/3-common-nx-commands.md
- apps/vscode/src/getting-started/4-projects.md
- apps/vscode/src/getting-started/5-streamlining.md
- apps/vscode/src/package.json
A recent VS Code update added experimental support for [Welcome Page walkthroughs](https://code.visualstudio.com/updates/v1_56#_welcome-page-walkthroughs).
I am only able to get the walkthrough to launch on installation in Insiders with the setting `"workbench.welcomePage.experimental.extensionContributions": true`.
But without Insiders, we still get this new button on the Welcome View to launch our walkthough:
The walkthrough docs were copied from nx.dev, minus the videos. I could not get external links to work from within the walkthrough so wasn't able to include those.
(just some previous research notes:)
> I also checked out what [GitLens](https://github.com/eamodio/vscode-gitlens) is doing with their welcome and latest updates content, which is a different direction we may want to …
> feat: welcome view and getting started walkthrough

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
Fixes the overflow on the configurations tabs menu when there are more configuration options than fit in the max-width of the container
> fix: configurations tabs overflow

- apps/vscode/src/main.ts
- libs/server/src/lib/telemetry/record.ts
- libs/server/src/lib/telemetry/sinks/google-analytics-sink.ts
This PR adds more analytics to track the current workspace type, being: `'nx', 'angular', 'angularWithNx'`.
> chore: add more analytics to track workspace type

- .github/workflows/publish.yml
- package.json
- yarn.lock
This PR enables publishing the extension to the open vsx registry in addition to the microsoft vscode extension marketplace.
Reasons for doing so are outlined in #1114 
Todos for the maintainers before completing PR:
- create an account on open vsix
- https://open-vsx.org/
- create a PAT token
- https://open-vsx.org/user-settings/tokens
- run the following once (locally) to create the nrwl namespace:    
`npx ovsx create-namespace nrwl -p REPLACE-WITH-PAT-TOKEN`
- create environment variable `OVSX_PAT` in the CI pipeline that holds the pat token
- done
Closes #995 
Closes #1114
> chore(osvx): publish extension to osvx registry

- libs/schema/src/index.ts
- libs/server/src/index.ts
- libs/server/src/lib/utils/read-projects.ts
- libs/server/src/lib/utils/read-schematic-collections.ts
- libs/server/src/lib/utils/utils.ts
- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
- libs/vscode/nx-workspace/src/lib/find-workspace-json-target.ts
- libs/vscode/nx-workspace/src/lib/verify-workspace.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
- libs/vscode/tasks/src/lib/cli-task-definition.ts
- libs/vscode/tasks/src/lib/cli-task-provider.ts
- libs/vscode/tasks/src/lib/cli-task-quick-pick-item.ts
- libs/vscode/tasks/src/lib/nx-task-commands.ts
- libs/vscode/verify/src/lib/verify-builder-definition.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
- workspace.json
This changes all mentions of the older workspace names (architect, builders, etc) to the newer one (targets, executors, etc)
> chore: change to workspace v2 names

- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
This removes the loading item from the projects view. This was causing some issues with some users where items were trying to be used before all the projects were loaded.
Initially this was added in this extension as a way to show that projects were loading (duh :joy:) because the parser used originally was terribly slow, and the vscode ui froze. With the quicker parser, we don't freeze the UI anymore, and this loading item is not needed. 
Potentially fixes #1126
> fix: remove loading item from projects view

- libs/vscode/nx-workspace/src/lib/verify-workspace.ts
This ensures that we are using the correct workspace configuration when verifying the workspace.
> fix: use proper workspace json path when verifying workspaces

- apps/vscode/src/main.ts
- apps/vscode/webpack.prod.config.js
- libs/server/src/lib/abstract-tree-provider.ts
- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
- libs/vscode/nx-workspace/src/lib/get-nx-config.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-config.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
- libs/vscode/nx-workspace/src/lib/verify-workspace.ts
- libs/vscode/nx-workspace/src/lib/workspace-codelens-provider.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
- libs/vscode/tasks/src/lib/cli-task-provider.ts
- libs/vscode/tasks/src/lib/nx-task-commands.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
- package-scripts.js
- package.json
- workspace.json
17.10.0 (average time (load code + call activate) - `769ms`)
```
| Extension                             | Eager | Load Code | Call Activate | Finish Activate | Event                                                 | By                                    |
| ------------------------------------- | ----- | --------- | ------------- | --------------- | ----------------------------------------------------- | ------------------------------------- |
| nrwl.angular-console                  | false | 309       | 499           | 0               | onStartupFinished                                     | nrwl.angular-console                  |
```
```
| Extension                             | Eager | Load Code | Call Activate | Finish Activate | Event …
```
> perf: decrease activation time

- package-scripts.js
Adding `lint` back to scripts definition, in order to support
`nps lint` command from CONTRIBUTING doc
fixes:
```bash
$ nps lint
Scripts must resolve to strings. There is no script that can be resolved from "lint"
```
Thanks!
> chore: missing `lint` command

- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.scss
Minor fix, removes warnings. Instead of using `math.div`, uses multiplier.
https://sass-lang.com/documentation/breaking-changes/slash-div
Thanks!
> style: migrate division syntax

- libs/server/src/lib/utils/utils.ts
- libs/vscode/nx-workspace/__mocks__/@nx-console/server.ts
- libs/vscode/nx-workspace/__mocks__/@nx-console/vscode/configuration.ts
- libs/vscode/nx-workspace/__mocks__/vscode.ts
- libs/vscode/nx-workspace/jest.config.js
- libs/vscode/nx-workspace/src/lib/verify-workspace.spec.ts
This commit adds sorting applied to projects found in workspace
configuration, before content is returned to the UI. Entries are sorted
using current environment locale settings.
- implementation
- tests
Thanks!
Closes #1111
> feat: sort projects in project view

- libs/vscode/nx-workspace/src/lib/get-nx-workspace-config.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
Ensure that workspace projects are properly resolved to the full configuration. The async nature of calling the workspace utils will cause the cache to be invalid
Fixes #1144
> fix: ensure that projects are properly resolved during async calls

- libs/server/src/lib/utils/utils.ts
Handles the non-existing files when trying to check if it's a real file. This will now return an empty object when the file does not exist.
Fixes #1169
> fix: handle non-existing files better and return an empty object

- libs/vscode/nx-workspace/src/lib/get-nx-config.ts
Properly handles workspaces that do not have a nx.json file.
Fixes https://github.com/nrwl/nx-console/issues/1168
> fix: handle non existant nx.json file better. Fixes pure angular workspaces.

- libs/server/src/lib/utils/get-generators.ts
- libs/server/src/lib/utils/read-collections.ts
This resolves individual schema.json file paths to the builder/executor path mentioned in the package.json. Before we did a join to get the paths, and it didnt properly resolve to the correct location 
Fixes #1174
> fix: resolve schema paths rather than joining

- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- apps/vscode/src/typescript-plugin.ts
- libs/server/src/index.ts
- libs/server/src/lib/utils/find-config.ts
- libs/server/src/lib/utils/watch-file.ts
- package.json
- tsconfig.base.json
- yarn.lock
Includes the `@monodon/typescript-nx-imports-plugin` to configure the typescript language service to include references to projects outside it's own tsconfig.
> feat: include typescript plugin for imports

- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- libs/typescript-plugin/.eslintrc.json
- libs/typescript-plugin/README.md
- libs/typescript-plugin/jest.config.js
- libs/typescript-plugin/package.json
- libs/typescript-plugin/project.json
- libs/typescript-plugin/src/index.ts
- libs/typescript-plugin/src/lib/typescript-plugin.ts
- libs/typescript-plugin/tsconfig.json
- libs/typescript-plugin/tsconfig.lib.json
- libs/typescript-plugin/tsconfig.spec.json
- libs/vscode/configuration/src/lib/configuration-keys.ts
- package.json
- tsconfig.base.json
- workspace.json
- yarn.lock
* Moves the typescript plugin file to it's own lib. 
* Adds configuration support to turn this on through the settings (default is off to make sure we test this)
> feat: add configuration support for the import plugin

- libs/server/src/lib/utils/utils.ts
When we moved away from using angular cli utils to get normalized options for a schema, it supposedly had some special check for path to make sure it's always visible. Now we're doing the same.
> fix: make the `path` option always visible when using generate

- apps/vscode/src/main.ts
- libs/typescript-plugin/src/lib/typescript-plugin.ts
This should potentially/hopefully fix some issues users are facing when trying to open workspaces with the latest versions. This essentially reverts to the old logic of "scanning" for a directory with workspace.json/angular.json and now nx.json.
> fix: revert to old logic for scanning workspaces, also fix checking for paths of undefined

- apps/vscode/src/package.json
In an effort to reduce startup costs for Nx Console, a change was made so that it only activated when workspaces contained workspace.json/angular.json/nx.json. This caused issues when users opened workspaces that contained subfoldered nx workspaces.
> fix: revert activationEvents to `onStartupFinished`

- apps/vscode/src/main.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
This PR checks to see if a required function exists on a local version of Nx. If it doesn't, then we fallback to the one that's include with Nx Console.
> fix: fallback to built in nx utils if required function doesnt exist

- libs/vscode/nx-workspace/src/lib/get-nx-workspace-config.ts
Lowers the version to manually load the configurations.
> fix: read configurations manually if Nx is lower than 12

- libs/server/src/lib/utils/utils.spec.ts
- libs/server/src/lib/utils/utils.ts
I've encountered an issue with some old repository. It contained a schematics, that didn't have `properties` field specified in `schema.json`. Schematics itself was working properly, but `nx-console` plugin failed to even launch. This PR adds handling of a case there's no `properties` field in schema.
@vsavkin would it be reasonable to also make `properties` field optional in the `Schema` interface in Nx repo [here](https://github.com/nrwl/nx/blob/master/packages/tao/src/shared/params.ts#L51)?
> fix: handle absence of "properties" in schema

- libs/server/src/lib/utils/get-generators.ts
Fixes running workspace schematics if the workspace version supports that instead of workspace generators
Fixes #1187
> fix: support workspace-generators and workspace-schematics

- apps/vscode/project.json
`tslint` is listed as `externalDependency` but is not used anymore
> fix: remove tslint from externalDependencies

- .github/workflows/ci_checks.yml
- .github/workflows/setup/action.yml
The `setup` action should use `actions/setup-node` **v2**. It supports caching internally so there is no need for the extra `actions/cache` step. 
Also the Agents are currently running the `actions/setup-node` step twice.
> fix: fixed CI Node Setup and Caching

- libs/server/src/lib/utils/get-generators.ts
Shows the description and title when trying to run a workspace generator/schematic
fixes #1224
> fix: show description when running workspace generators/schematics

- package.json
- yarn.lock
@Cammisuli I'm sorry to bother you again, but `ovsx` v3.0.0 updates the in ovsx used `vsce` to ^2.6.3 which is the same version the repo uses. It was just released 10h ago.
> chore: updated ovsx to ^0.3.0

- apps/vscode-ui/.browserslistrc
- package.json
- yarn.lock
`vscode@^1.50.0` uses `electron@9.2.1` so it can be written as browserslist query to get the correct chrome versions.
> chore: fixed browserslist queries

- libs/vscode-ui/components/src/lib/field/field.component.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.html
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
While in the UI form for generators/schematics, we can now press cmd + enter (or ctrl+enter for non macOS environments) to execute the form. 
closes #1217
> feat: use cmd/ctrl+enter to execute generator while in the UI form

- libs/npm/src/lib/workspace-dependencies.spec.ts
- libs/npm/src/lib/workspace-dependencies.ts
Allows local executors to be run with Nx console
fixes #1180
> fix: run executors that are local to the workspace (ie local executors)

- package.json
- yarn.lock
Packages that don't need to be explicitly listed as a dependency:
- copy-webpack-plugin
- webpack-merge
- webpack-node-externals
Unused Packages: 
- husky
- pretty-quick
> chore: removed unused packages to speed up install

- libs/npm/src/lib/pnp-dependencies.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
- package.json
- yarn.lock
This calls `pnp.setup()` so that it can patch the node `require` so that we can load the `@nrwl/workspace` package from yarn 2+
> fix: run pnp.setup to patch require

- libs/server/src/lib/utils/read-collections.ts
This makes sure that when we check for duplicate collections, we check the type as well. This fixes an issue where generators and executors have the same name, and one or the other gets filtered out.
> fix: check for duplicate collections based on type

- libs/server/src/lib/utils/read-projects.ts
Make sure to read both the builder and executor schema's
Fixes #1251
> fix: make sure to read schemas from both builders and executors for builder

- apps/vscode/src/main.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/format-task/format-task.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
- libs/vscode/nx-run-target-view/src/lib/run-target-tree-item.ts
- libs/vscode/nx-run-target-view/src/lib/run-target-tree-provider.ts
- libs/vscode/nx-workspace/src/lib/reveal-workspace-json.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
+ Makes the "Generate & Run Target" view list all (and only) targets that you support in your workspace
+ (Generate and Run targets are still there)
+ Makes this pane update on changes to workspace configuration (on save)
> feat: making the contents of the run target view match the workspace

- libs/npm/src/lib/workspace-dependencies.spec.ts
- libs/npm/src/lib/workspace-dependencies.ts
This checks to make sure that the fileType is checking with the bit flag. VSCode shows that the `type` can be both a directory or a symbolic link. And we need to make sure we check for both instances
> fix: check if dependency path type is directory with bit flag

- libs/schema/src/index.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
This makes sure that positionals are properly checked. Since positionals start at `0`, JavaScript is very kind and thinks that 0 is false. So Nx Console never thought that positional 0 was valid. This caused issues with some schemas that had multiple positionals because then arguments went out of order.
This also includes a check for `x-dropdown` to see if `projects` is specified. This will allow Nx Console to display this property with the project dropdown/autocomplete. 
Fixes #1261
> fix: properly check positional argument for generating with UI

- libs/server/src/lib/utils/utils.spec.ts
- libs/server/src/lib/utils/utils.ts
This makes sure that required properties are sorted near the top of the list (there are still some properties that are more important)
Fixes #1265
> fix: sort properties by required

- libs/vscode-ui/feature-task-execution-form/src/lib/format-task/format-task.pipe.spec.ts
- libs/vscode-ui/feature-task-execution-form/src/lib/format-task/format-task.ts
In certain versions of Angular CLI using the short form `--prod` does not work. This changes that so that all configurations are not short cutted and instead use the full configuration name. 
Fixes #1281
> fix: always use full `--configuration` flag

- apps/vscode/src/main.ts
- libs/server/src/index.ts
- libs/server/src/lib/check-is-nx-workspace.ts
- libs/server/src/lib/utils/build-project-path.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-config.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts
- libs/vscode/nx-workspace/src/lib/nx-version.ts
- libs/vscode/nx-workspace/src/lib/reveal-workspace-json.ts
- libs/vscode/nx-workspace/src/lib/verify-workspace.ts
- libs/vscode/nx-workspace/src/lib/workspace-codelens-provider.ts
- libs/vscode/tasks/src/lib/cli-task.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
Uses the Nx Project graph to get the proper targets for package.json files and projects that do target inference. And because of this, we're able to support Lerna workspaces that have nx enabled with `useNx` set to true. 
Fixes #1202
Fixes #1289
> feat: support package.json projects

- libs/vscode/webview/src/lib/get-task-execution-schema.ts
+ fixes camel case targets so they still work in the generate and run target pane
> fix: camel case targets not working in generate & run target pane

- libs/server/src/lib/utils/get-generators.ts
- libs/server/src/lib/utils/ng-version.ts
- libs/server/src/lib/utils/read-projects.ts
- libs/server/src/lib/utils/utils.spec.ts
- libs/server/src/lib/utils/utils.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
- libs/vscode/tasks/src/lib/select-generator.ts
- libs/vscode/verify/src/lib/verify-builder-definition.ts
- libs/vscode/webview/src/lib/get-task-execution-schema.ts
> fix: hyphenate arguments for ng workspaces

- apps/vscode/src/package.json
- libs/vscode/configuration/src/lib/configuration-keys.ts
- libs/vscode/tasks/src/lib/select-generator.ts
Adds new settings to enable filtering of the generator list within Nx Console. 
These settings are "nxConsole.enableGeneratorFilters", "nxConsole.generatorAllowlist", "nxConsole.generatorBlocklist".
The allow and block lists can be combined, where the allow list takes priority, then the block list is applied to the remaining items. 
Fixes #1272
> feat: add an allowlist and a blocklist for generators

- libs/schema/src/index.ts
- libs/server/src/lib/utils/utils.ts
- libs/vscode/tasks/src/lib/select-generator.ts
> fix: handle hyphenation when looking for generator defaults

- .eslintrc.json
- libs/vscode/nx-commands-view/src/lib/nx-commands-provider.ts
- libs/vscode/nx-help-and-feedback-view/src/lib/nx-help-and-feedback-provider.ts
Some arguments have to remain unused and it's a good pattern used in nx console to name them `_`.
This PR specifically allows that instead of having to use eslint ignores.
> chore: allow unused arguments if they are named '_'

- CONTRIBUTING.md
Hi @Cammisuli, I saw that you changed #1332 & #1334 to be "chore: ...." which I agree is the correct type here.
However, "chore" was not listed as an allowed type in `CONTRIBUTING.MD` so I added the correct types as they are validated by the `pr_title` action for clarity.
> docs: correctly document all allowed scopes

- apps/vscode/src/main.ts
- apps/vscode/src/package.json
- libs/shared/collections/src/lib/get-executors.ts
- libs/shared/collections/src/lib/get-generators.ts
- libs/shared/collections/src/lib/read-collections.ts
- libs/vscode/add-dependency/.eslintrc.json
- libs/vscode/add-dependency/README.md
- libs/vscode/add-dependency/jest.config.ts
- libs/vscode/add-dependency/project.json
- libs/vscode/add-dependency/src/index.ts
- libs/vscode/add-dependency/src/lib/add-dependency-codelens-provider.ts
- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
- libs/vscode/add-dependency/tsconfig.json
- libs/vscode/add-dependency/tsconfig.lib.json
- libs/vscode/add-dependency/tsconfig.spec.json
- libs/vscode/nx-commands-view/project.json
- libs/vscode/nx-commands-view/src/lib/nx-commands-provider.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-tree-item.ts
- libs/vscode/tasks/src/index.ts
- tsconfig.base.json
- workspace.json
In order to make it easier to add dependecies and execute their corresponding init generators, a command that guides you through the process has been added.
> feat: add dependency functionality

- libs/vscode/project-graph/src/lib/graph-webview.ts
Makes sure that all graph actions send the "GET_CONTENT" xstate action to make sure that the state always starts from the beginning.
> fix: always send "GET_CONTENT" for graph actions

- apps/vscode/src/package.json
- libs/vscode/configuration/src/lib/global-configuration-store.ts
- package.json
- yarn.lock
@types/vscode now at 1.71.1 (with quickpick seperator api!)
> chore: update vscode

- apps/nxls/src/main.ts
- libs/language-server/capabilities/code-completion/src/lib/get-completion-items.spec.ts
- libs/language-server/capabilities/document-links/src/lib/get-document-links.spec.ts
- libs/language-server/utils/src/lib/json-language-service.ts
- libs/language-server/utils/src/lib/language-model-cache.ts
Sets the json language service to return undefined. This makes all other places handle the undefined service if it doesnt get created. 
Fixes #1359
> fix: handle non existent json service

- README.md
> docs: update supported VSCode badge to ^1.71.0

- apps/vscode-e2e/specs/utils.ts
test was flaky because of improper wait command
> fix: wait for nx console viewcontrol

- apps/vscode/src/commands/refresh-workspace.ts
- libs/shared/workspace/src/lib/get-nx-workspace-config.ts
- libs/shared/workspace/src/lib/get-nx-workspace-package.ts
- libs/shared/workspace/src/lib/workspace.ts
fix https://github.com/nrwl/nx-console/issues/1362
> feat: check if nx daemon is enabled

- libs/vscode/nx-help-and-feedback-view/src/lib/nx-help-and-feedback-provider.ts
https://github.com/nrwl/nx/pull/12942 broke the connect-to-nx-cloud command so we have to check for that version now.
> fix: alias 'connect-to-nx-cloud' to 'connect'

- libs/vscode/nx-workspace/src/lib/find-project-with-path.ts
before: right clicking on a lib in a standalone project and selecting `nx generate` would infer the project path to be the root project.
after: correctly infers the lib as the clicked project.
> fix: correctly infer project path in standalone workspace

- libs/vscode/nx-cloud-view/src/lib/auth/nx-cloud-authentication-provider.ts
- libs/vscode/nx-cloud-view/src/lib/auth/oauth.service.ts
- libs/vscode/nx-cloud-view/src/lib/config.ts
- libs/vscode/nx-cloud-view/src/lib/init-nx-cloud-onboarding-view.ts
- libs/vscode/nx-cloud-view/src/lib/nx-cloud-service/nx-cloud-api.service.ts
- libs/vscode/nx-cloud-view/src/lib/nx-cloud-service/nx-cloud-service.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace.ts
- fix: override dev or prod mode via cloud runner url
- chore: repsect dev or prod mode when setting up cloud runner
> fix: consider dev/prod mode in more scenarios

- libs/language-server/capabilities/code-completion/src/lib/get-completion-items.spec.ts
- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
- libs/language-server/workspace/src/lib/workspace.ts
- libs/shared/types/src/lib/nx-workspace.ts
- libs/vscode/nx-run-target-view/src/lib/run-target-tree-item.ts
- libs/vscode/nx-run-target-view/src/lib/run-target-tree-provider.ts
- libs/vscode/tasks/src/lib/cli-task-commands.ts
With an upcoming release of Nx, workspace.json support is completely removed. There was a function being used here that expected those config files, but Nx Console hasnt used that in quite a while. So it is safe to remove that function.
> fix: remove the usage of configurationPath

- libs/vscode/nx-cloud-view/src/webview/components/status-labels.ts
I also added a small hover text so people aren't confused when it's truncated
> fix: truncate status label text for cloud integration

- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/run_generator/run_task.kt
ideally, we would reimplement nx devkit here or wrap it in the lsp because there are some more nuances regarding which command to use:
https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/package-manager.ts#L81
for now I think it's fine to use the naive version.
> chore(intellij): use yarn instead of yarn exec

- apps/vscode/src/package.json
- libs/vscode/tasks/src/lib/cli-task-commands.ts
- libs/vscode/tasks/src/lib/select-re-move-generator.ts
fixes https://github.com/nrwl/nx-console/issues/1545
Since `nx.remove.fileexplorer` wasn't really specific to the file explorer, I renamed it to `nx.remove` and made the `Uri` param optional.
> fix(vscode): fix running (re)move from command prompt

- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/NxGenerateUiAction.kt
This PR will add custom renderer to the nx generate ui popup to include description name and description
> feat(intellij): set custom renderer for nx generate ui popup

- apps/intellij/src/main/kotlin/dev/nx/console/generate_ui/run_generator/RunGeneratorManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxExecutable.kt
- apps/intellij/src/main/resources/messages/NxConsoleBundle.properties
This will use the local install of Nx to run the generate command. This removes the need to check for package managers and just run nx directly.
Should also enable easier support when we move to standalone nx
> fix(intellij): use the local binary for nx generate instead of package managers

- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-provider.ts
- libs/vscode/nx-conversion/src/lib/vscode-nx-conversion.ts
- libs/vscode/project-graph/src/lib/create-project-graph.ts
- libs/vscode/project-graph/src/lib/graph.machine.spec.ts
- libs/vscode/tasks/src/lib/cli-task-provider.ts
- libs/vscode/tasks/src/lib/cli-task.ts
- libs/vscode/tasks/src/lib/nx-task-commands.ts
- libs/vscode/tasks/src/lib/nx-task.ts
- libs/vscode/utils/src/lib/shell-execution.ts
Using the nxls we can check if the workspace has an encapsulated version of Nx. And if so, we change all the shell executions to run with `./nx` or `./nx.bat`
> feat(vscode): run commands with encapsulated nx (#1557

- libs/generate-ui/feature-task-execution-form/src/lib/task-execution-form/task-execution-form.component.scss
> fix(generate-ui): make sure the form is centered correctly on large screens

- libs/language-server/workspace/src/lib/get-generator-context-from-path.ts
When generating with the context menu, (depending where the context menu is initialized) sometimes we get the workspace layout directory prefilled. This causes generates to create a duplicated nested folders. (ie, `libs/libs`)
> fix(nxls): do not include workspace layout in directory context for generate calls

- apps/intellij/src/main/resources/META-INF/plugin.xml
This PR should add suggestion for installing plugin when finding nx javascript dependency in the project
Like for stylus here below
It should be available after publishing this to marketplace
> feat(intellij): suggest installing plugin by dependency support

- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/NxGenerateUiFile.kt
the browser will now load the correct background color as soon as it's loaded instead of after communicating with the IntelliJ. Not sure how to eliminate the remaining flicker.
> fix(intellij): slightly reduce generate-ui white flicker

- apps/intellij/src/main/kotlin/dev/nx/console/cli/NxCreateWorkspaceProjectGenerator.kt
this isn't the greatest solution but it works for now. 
Before, the field would show a new version but npx cache would pick up an outdated one.
Ideally, we would have a custom UI here that lets you pick the version etc.
> fix(intellij): use latest by default when creating a new workspace

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- apps/nxls/src/main.ts
> fix(nxls): use `workspaceFolders` before `rootUri` for better Windows path compatibility

- apps/intellij/build.gradle.kts
- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/nxls/src/main.ts
- libs/language-server/types/src/index.ts
- libs/language-server/workspace/src/lib/create-project-graph.ts
- libs/language-server/workspace/src/lib/get-project-graph-output.ts
- libs/shared/utils/src/lib/get-nx-execution-command.ts
- libs/vscode/project-graph/src/lib/graph.machine.ts
In vscode, nxls is started via a fork and communicates with ipc. So messages on stdio will not affect the communication.
With Intellij, the nxls is started with a separate process and communicates with stdio. This means that any `exec` calls that are called within the language server could pollute the stdio communicate and cause the process to exit. So we have to make sure that we set exec calls to `stdio: ignore`.
This also fixes the nx graph to show up properly in Windows.
> fix(nxls): do not output exec to stdio (#1644

- apps/intellij/src/main/kotlin/dev/nx/console/ide/ConsoleFolding.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
Simplifies the console/terminal output to hide the long path for the nx executable.
Before:
After:
> feat(intellij): add console folding

- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunActionGroup.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/getOrCreateRunnerAndConfigurationSettings.kt
Running the `Nx Run Target` from the command prompt or context menu finds the proper run configuration now. Before it always selected the first one without checking if it was the proper run configuration
> fix(intellij): find the proper run configuration settings for nx targets

- apps/intellij/src/main/kotlin/dev/nx/console/telemetry/measurementProtocol/MeasurementProtocolTelemetryService.kt
> fix(intellij): use warn instead of error for caught exceptions

- libs/vscode/tasks/src/lib/cli-task-commands.ts
Shows only projects that have the requested run target when clicking items in the Run Target view and the Nx: Run Target command prompt
> fix(vscode): run target filters projects

- apps/vscode/package.json
fixes #1682
I missed some more options that I initially tried to remove in https://github.com/nrwl/nx-console/pull/1672
> fix(vscode): remove obsolete commands

- apps/intellij/src/main/kotlin/dev/nx/console/utils/DocumentUtils.kt
Includes `package.json` in the list of nx files so that we can attach the lsp to.
> fix(intellij): include package.json for nx file types

- libs/vscode/tasks/src/lib/cli-task-commands.ts
> fix(vscode): get projects properly in cli-task-command

- apps/intellij/src/main/kotlin/dev/nx/console/graph/actions/NxGraphFocusTaskAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/models/NxTarget.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxProjectsTreeStructure.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxSimpleNode.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxToolWindowFactory.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandConfiguration.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationEditor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationProducer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxTaskExecutionManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/getOrCreateRunnerAndConfigurationSettings.kt
this adds functionality to the toolwindow so that configurations are shown. You can run them directly from there or configure them first.
> feat(intellij): display target configurations in the toolwindow & run configuration editor

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGenerateRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGenerateService.kt
before we passed the full generator name (e.g. `@nx/react:component`) to the nxls instead of just `component`. This meant that the workspace default lookup broke and default values weren't correctly displayed. 
That's fixed now.
> fix(intellij): fix default values in webview by passing correct name to nxls

- apps/vscode/package.json
- libs/vscode/nx-cloud-view/src/lib/auth/nx-cloud-authentication-provider.ts
in case something goes wrong during login, we might get faulty session data - this way we can just clear it and try again
> feat(vscode): add command to clear nx cloud session storage manually

- apps/vscode-e2e/testworkspaces/testworkspace-nested/src/environments/environment.prod.ts
- apps/vscode-e2e/testworkspaces/testworkspace-nested/src/environments/environment.ts
- apps/vscode/src/main.ts
- libs/vscode/nx-cloud-view/src/lib/nx-cloud-service/nx-cloud-service.ts
with esbuild, `fileReplacements` isn't a thing anymore so `environment.production` is useless. 
Switched to the tried and true `context.extensionMode === ExtensionMode.Development`
> fix(vscode): fix cloud view connecting to staging

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGeneratorSearchEverywhereContributorFactory.kt
Calling `runBlocking` on a init field could cause the plugin to potentially freeze the UI. 
Moving this to `invokeLater` where it's actually needed seems to improve performance.
> fix(intellij): do not use `runBlocking` for SearchEverywhereContributor

- apps/generate-ui-v2-e2e/src/e2e/generator-context.cy.ts
- apps/generate-ui-v2/src/ide-communication.controller.ts
- libs/language-server/workspace/src/lib/get-project-by-path.ts
fixes two things: 
- compare normalized paths in nxls to make sure detecting the project based on the path works 
- don't autofill `directory` if `project` also exists. For example this broke `@nx/react:component`. This is only until the current effort to standardize path/dir options is done in nx and we can be more consistent here.
> fix: adjust generator autofilling

- apps/generate-ui-v2-e2e/src/e2e/app.cy.ts
- apps/generate-ui-v2-e2e/src/support/visit-generate-ui.ts
- apps/generate-ui-v2/src/components/button.ts
- apps/generate-ui-v2/src/components/icon.ts
- apps/generate-ui-v2/src/form-values.service.ts
- apps/generate-ui-v2/src/main.ts
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/GenerateUiMessages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/V2NxGenerateUiFile.kt
- apps/intellij/src/main/resources/generate_ui_v2/icons/chevron-down.svg
- apps/intellij/src/main/resources/generate_ui_v2/icons/chevron-up.svg
- apps/intellij/src/main/resources/generate_ui_v2/icons/close.svg
- apps/intellij/src/main/resources/generate_ui_v2/icons/copy.svg
- apps/intellij/src/main/resources/generate_ui_v2/icons/search.svg
- libs/shared/generate-ui-types/src/lib/messages.ts
also updated icons to match the ones from the new ui instead of the old one. (`AllIcons/expui/general`)
> feat(generate-ui): add copy to clipboard button to generate ui

- libs/vscode/nx-cloud-view/src/webview/components/no-cache.ts
- libs/vscode/nx-cloud-view/src/webview/main.ts
This is what it looks like now: 
Before, the button was hidden if all other views were open (the default state). Now you can see the button either way:
> feat(vscode): rearrange empty state for nx cloud view to make button more prominent

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxToolWindowFactory.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandConfiguration.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationProducer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxTaskExecutionManager.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/getOrCreateRunnerAndConfigurationSettings.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/ProjectJsonPSIUtils.kt
When we build an Intellij Run Configuration with an nx target that has a configuration (ie, `nx run project:target:configuration`) the saved Intellij Run Configuration goes missing when restarting the IDE.
Now everything should be saved properly and a previously created run configuration can run properly.
> fix(intellij): save and load run configurations that have a nx target configuration set

- apps/intellij/src/main/kotlin/dev/nx/console/ProjectPostStartup.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/NxFocusTargetInGraphLineMarkerContributor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsWrapper.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/requests/NxProjectsByPathsRequest.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxRunConfigurationProducer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxProjectJsonToProjectMap.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/ProjectJsonPSIUtils.kt
- apps/nxls/src/main.ts
- libs/language-server/types/src/index.ts
- libs/language-server/workspace/src/lib/get-project-by-path.ts
- I implemented a `NxProjectJsonToProjectMap` that keeps track of all projects matching the project.json files. When we create gutter actions, we can synchronously read from that map to find out what project the file belongs to without relying on the optional name property
- the map is prefilled with values at startup or when the workspace changes
- we fall back to the name property if the map is empty for some reason (maybe race conditions or the nxls is gone)
- to scale this for bigger workspaces, this required a new nxls request to efficiently find projects for multiple paths
> fix: enable gutter actions in project.json without name & refactor project by path request

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/tree/builder/NxTreeBuilderBase.kt
- libs/language-server/workspace/src/lib/get-project-folder-tree.ts
- libs/vscode/nx-project-view/src/lib/views/nx-project-tree-view.ts
sort the tree view. VSCode is sorted to have root folders first and then root projects because it looks very chaotic otherwise.
Thx [@ctaepper](https://github.com/ctaepper) for pointing this out
> fix: sort project tree view / nx toolwindow

- apps/generate-ui-v2/src/components/search-bar.ts
- libs/vscode/generate-ui-webview/src/lib/generate-ui-webview.ts
Some examples of how it looks:
> feat: show keyboard shortcut indicator in generate ui search bar

- apps/vscode/package.json
- libs/vscode/project-graph/src/lib/project-graph.ts
Before, if you wanted to focus a project from the command prompt, it would only look for the currently opened file and fail otherwise. 
Now it will fall back to showing a quickpick and letting the user manually select a project if the currently opened file doesn't belong to a project.
This is not the same as the intellij behavior but it's a step in the right direction and more robust.
> fix(vscode): enhance graph/task focus commands to fallback to manual selection

- apps/intellij/src/main/kotlin/dev/nx/console/settings/options/WorkspacePathSetting.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxBasePath.kt
since the workspace path is a project setting and as such can be shared between team mates, it doesn't really make much sense to have absolute paths in here.
Now the settings takes a relative path which is then resolved to the full path when needed. The full path is still shown because it looks better but under the hood it's saved as a relative path to make the setting shareable.
> fix(intellij): make workspace path setting relative to project base path

- apps/generate-ui-v2-e2e/src/support/visit-generate-ui.ts
- apps/intellij/build.gradle.kts
- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- libs/generate-ui/feature-task-execution-form/src/lib/ide-communication/ide-communication.service.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace.ts
- libs/vscode/project-graph/src/lib/graph-webview.ts
- libs/vscode/project-graph/src/lib/load-html.ts
This will enable the opening of files by clicking on project edge links in the integrated graph.
We set `window.environment = 'nx-console'` to let the graph know it's rendered in nx console. 
Because this wasn't the case before and would break some things, it's only enabled from 17.0.0.
Once the nx change is released, we can change this number to reflect the actual release.
Corresponding nx PR: https://github.com/nrwl/nx/pull/18113
Let's wait until it's reviewed before merging.
> feat: consume new graph events to open files in the ide

- apps/generate-ui-v2/src/form-values.service.ts
fixes https://github.com/nrwl/nx-console/issues/1851
Also handles some more cases. Let's assume an option description: 
- `test with spaces` becomes `--description="test with spaces"`
- `hey what's up` becomes `--description="hey what's up"`
- `test with "spaces"` becomes `--description='test with "spaces"'`(<- note the outside single quotes to make sure the whole string is in the arg)
If you use both `"` and `'` in your arg I can't help you and you have to escape it manually. 
Are there any other cases that come to mind?
> fix(generate-ui): make sure arguments with spaces or quotes are handled correctly

- apps/generate-ui-v2-e2e/src/e2e/generator-context.cy.ts
- apps/generate-ui-v2/src/ide-communication.controller.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/filter-internal-and-deprecated-processor.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/index.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/temp-no-project-and-dir-processor.ts
before, fields with `x-deprecated` set were mistakenly not filtered. I added this and also moved the filtering logic to internal plugins to simplify the app.
> feat(generate-ui): filter deprecated fields & move functionality to plugins

- apps/generate-ui-v2/src/components/banner.ts
- apps/generate-ui-v2/src/components/icon.ts
- apps/generate-ui-v2/src/ide-communication.controller.ts
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/GenerateUiMessages.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/V2NxGenerateUiFile.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/services/NxlsService.kt
- apps/nxls/src/main.ts
- libs/language-server/types/src/index.ts
- libs/language-server/workspace/src/index.ts
- libs/language-server/workspace/src/lib/nx-console-plugins.ts
- libs/shared/generate-ui-types/src/lib/messages.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/git-clean-message-factory.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/index.ts
- libs/shared/nx-console-plugins/src/lib/nx-console-plugin-types.ts
- libs/vscode/generate-ui-webview/src/lib/generate-ui-webview.ts
- libs/vscode/nx-workspace/src/lib/nx-console-plugin-requests.ts
moves startup message plugin handling to nxls to enable it in both vscode & intellij. You can write plugins to display startup messages in 
Creates an internal plugin to dynamically display a warning message when generating with unstaged files.
> feat: write internal git clean startup message plugin & display startup messages in intellij

- apps/intellij/src/main/kotlin/dev/nx/console/graph/actions/NxGraphFocusProjectAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/actions/NxGraphFocusTaskAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/actions/NxGraphFocusTaskGroupAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/ui/NxGraphBrowser.kt
there's now a shortcut in the gutter and the toolwindow
`ctrl shift g` because it's the same as `ctrl shift r` for running a target but `g` for graph.
There's something funky going on breaking shortcuts when you open the gutter actions with `option enter`... but that seems like a separate concern from this PR.
> fix(intellij): add shortcut to focus task action

- libs/vscode/nx-project-view/src/lib/nx-tree-item.ts
- libs/vscode/nx-project-view/src/lib/views/nx-project-base-view.ts
- libs/vscode/nx-project-view/src/lib/views/nx-project-tree-view.ts
saves a click if there's only one project... no use in keeping it collapsed
> fix(vscode): expand root node if project view contains only single project

- libs/language-server/workspace/src/lib/nx-console-plugins.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/project-name-and-root-plugin.ts
- libs/shared/nx-console-plugins/src/lib/nx-console-plugin-types.ts
- libs/shared/types/src/lib/nx-workspace.ts
You can toggle `projectNameAndRootFormat` globally using `nx.json -> workspaceLayout`. Nx Console wasn't taking this into account. Now it is
> fix: take nx.json projectNameAndRootFormat config into account in generate ui

- apps/intellij/src/main/kotlin/dev/nx/console/run/NxCommandLineState.kt
This makes sure that when running Nx targets in wsl, that we use the correct linux path, rather than the Windows one (ie, use `/home/users/.../` rather than `//wsl$/home/users/..`)
> fix(intellij): fix running nx targets in wsl

- libs/vscode/nx-cloud-view/src/lib/nx-cloud-service/nx-cloud-service.ts
Make sure users can't try and connect to VSCode if they don't have access. The URL would have an undefined org and cause issues in the cloud app.
> fix(vscode): handle vcs integration click if user doesn't have access to workspace

- apps/vscode/package.json
- apps/vscode/src/main.ts
- libs/vscode/configuration/src/lib/configuration-keys.ts
- libs/vscode/configuration/src/lib/global-configuration-store.ts
- libs/vscode/nvm-tip/.eslintrc.json
- libs/vscode/nvm-tip/project.json
- libs/vscode/nvm-tip/src/index.ts
- libs/vscode/nvm-tip/src/lib/nvm-tip.ts
- libs/vscode/nvm-tip/tsconfig.json
- libs/vscode/nvm-tip/tsconfig.lib.json
- tsconfig.base.json
Shows a notification on startup alerting users about the currently loaded node version.
Also links to the new [Troubleshooting Recipe](https://nx.dev/recipes/nx-console/console-troubleshooting#vscode-nvm-issues) so folks can fix things before digging through GitHub issues. 
Can be turned on/off via settings.
> feat(vscode): show node version loaded by vscode on startup

- libs/vscode/nx-cloud-view/src/lib/config.ts
- libs/vscode/nx-cloud-view/src/lib/nx-cloud-service/nx-cloud-service.ts
- libs/vscode/nx-workspace/src/lib/get-nx-workspace.ts
In nx17, nx cloud can be configured without the `taskRunnerOptions` object. Nx Console can now deal with this format.
> fix(vscode): handle new nx cloud access token format in v17

- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
This reverts commit e55e3a8231eb51858e26eea7c1057b03159592d6.
> fix: revert don't process targets with hidden property (#1897)

- apps/intellij/src/main/kotlin/dev/nx/console/generate/ui/file/NxGenerateUiFileRenderer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/ui/Notifier.kt
Surfaces JCEF errors so the users knows what's going on.
should fix https://github.com/nrwl/nx-console/issues/1903
> fix(intellij): make sure jcef is supported before opening

- libs/vscode/generate-ui-webview/src/lib/generate-commands.ts
- libs/vscode/nx-cli-quickpicks/src/lib/select-generator.ts
- libs/vscode/nx-cli-quickpicks/src/lib/select-re-move-generator.ts
- libs/vscode/nx-cli-quickpicks/src/lib/select-run-information.ts
- libs/vscode/project-graph/src/lib/graph-webview.ts
- libs/vscode/project-graph/src/lib/project-graph.ts
- libs/vscode/utils/src/index.ts
- libs/vscode/utils/src/lib/empty-state-messages.ts
This PR adds some checks to make sure we don't get empty quickpicks or just nothing happening when users haven't installed dependencies yet.
> fix(vscode): handle missing node_module states more gracefully

- apps/generate-ui-v2/src/components/fields/multiselect-field.ts
- apps/generate-ui-v2/src/components/fields/select-field.ts
- libs/shared/schema/src/normalize-schema.ts
fixes https://github.com/nrwl/nx-console/issues/1919
I know this is more of a bandaid than an actual fix but since it's quite an edge case, I won't do the complicated fix with Labels.  If the objects are too long to fit in the field, you can hover over it. 
If it's super important to you, I'd be glad to help with a contribution!
> fix: stringify prompt items to avoid [object Object]

- libs/shared/nx-console-plugins/src/lib/internal-plugins/prefill-project-and-dir-processor.ts
Makes the prefilling logic smarter: 
- pre nx 17
- `project` option exists: prefill `project` and set`directory` to empty string
- `directory` option exists (and no `project`): prefill `directory`
- nx 17
- `projectNameAndRootFormat` or `nameAndDirectoryFormat` exist: prefill `directory` as `cwd`
- else: prefill `project`
- nx 18+ (when `as-provided` will become default and most `project` options will be removed)
- if project exists: prefill `project`
- else: prefill `directory` as `cwd`
> fix: distinguish more cases when prefilling

- apps/intellij/src/main/kotlin/dev/nx/console/nxls/managers/DocumentManager.kt
_should_ fix https://github.com/nrwl/nx-console/issues/1946 (can't repro tho)
> fix(intellij): don't try to remove document listener twice

- apps/intellij/src/main/kotlin/dev/nx/console/ide/DotNxFolderExcludeContributor.kt
- apps/intellij/src/main/resources/META-INF/plugin.xml
- gradle.properties
stuff in `.nx` isn't picked up anymore
Bumps required version to `2023.3` (branch `233`)
> feat(intellij): exclude .nx folder from js/ts service

- apps/nxls/src/main.ts
- apps/vscode/package.json
- libs/language-server/types/src/index.ts
- libs/language-server/workspace/src/index.ts
- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
- libs/language-server/workspace/src/lib/get-source-map.ts
- libs/vscode/nx-workspace/src/index.ts
- libs/vscode/nx-workspace/src/lib/get-source-map.ts
- libs/vscode/project-details/src/lib/init-vscode-project-details.ts
- libs/vscode/project-details/src/lib/project-details-manager.ts
Any file that contributes to a project will get a `Open PDV to Side` button (before just project.json & package.json).
In order to include all `package.json` files as a natural entry point, all `package.json` files that are siblings of a file that contributes to a project also get the same button.
> fix(vscode): show pdv open to side button on all files that define a project

- apps/intellij/src/main/kotlin/dev/nx/console/graph/NxGraphBrowserBase.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/NxGraphServer.kt
- apps/intellij/src/main/kotlin/dev/nx/console/graph/OldNxGraphBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/NxlsService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/client/NxlsLanguageClient.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nxls/server/NxService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectDetailsBrowser.kt
- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectDetailsEditorWithPreview.kt
- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectDetailsFileEditorProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/settings/NxConsoleSettingsProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/NxVersionUtil.kt
- libs/language-server/types/src/index.ts
- libs/language-server/watcher/src/lib/watcher.ts
- libs/language-server/workspace/src/lib/get-nx-version.ts
- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
- libs/language-server/workspace/src/lib/workspace.ts
- libs/vscode/nx-workspace/src/lib/get-nx-version.ts
- libs/vscode/project-details/src/lib/init-vscode-project-details.ts
- libs/vscode/project-details/src/lib/project-details-preview.ts
- libs/vscode/project-graph/src/lib/init-vscode-project-graph.ts
- libs/vscode/project-graph/src/lib/legacy-implementation/load-html.ts
- listen to graph error states in intellij
- update nxVersion command to use the new request instead of reading from workspace()
- fix color updating in intellij webview
> fix: handle error states better, especially in intellij

- apps/nxls/src/main.ts
- libs/language-server/capabilities/code-completion/src/lib/schema-completion.ts
- libs/language-server/capabilities/definition/.eslintrc.json
- libs/language-server/capabilities/definition/README.md
- libs/language-server/capabilities/definition/jest.config.ts
- libs/language-server/capabilities/definition/package.json
- libs/language-server/capabilities/definition/project.json
- libs/language-server/capabilities/definition/src/index.ts
- libs/language-server/capabilities/definition/src/lib/get-definition.ts
- libs/language-server/capabilities/definition/tsconfig.json
- libs/language-server/capabilities/definition/tsconfig.lib.json
- libs/language-server/capabilities/definition/tsconfig.spec.json
- libs/language-server/capabilities/hover/src/lib/get-hover.ts
- libs/language-server/types/src/index.ts
- libs/language-server/utils/src/index.ts
- libs/language-server/utils/src/lib/executor.ts
- libs/language-server/workspace/src/lib/get-executors.ts
- libs/language-server/workspace/src/lib/get-generators.ts
- libs/language-server/workspace/src/lib/read-collections.ts
- libs/shared/json-schema/src/lib/create-builders-and-executors-schema.ts
- libs/shared/schema/src/schema.ts
- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
- libs/vscode/nx-cli-quickpicks/src/lib/select-generator.ts
- libs/vscode/nx-workspace/src/lib/get-generators.ts
- package.json
- tsconfig.base.json
- yarn.lock
Implements the Go To Definition functionality requested in https://github.com/nrwl/nx-console/issues/1936 for VSCode
1. Refactored `CollectionInfo` to a union type for better typing
2. Duplicated the `hover` package and changed references to `definition`
3. Implemented the `goToDefinition` capability 
Verified that it worked in the nx repo and my own repo
https://github.com/nrwl/nx-console/assets/20645805/8c814979-3f9e-4b3c-ac42-8d0165f66c49
> feat: go to executor definition

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGenerateRunAnythingProvider.kt
- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxGenerateService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/models/NxGenerator.kt
Trying to launch the generate ui fails to open. This is because the schema changed from the language server, which caused the `NxGenerator` data class in the kotlin side to serialize with missing data
The `NxGenerator` data class now has the same property name as the nxls, which will allow proper serialization and open the generate ui window
> fix(intellij): fix generate ui

- .editorconfig
- apps/intellij/src/main/kotlin/dev/nx/console/ide/project_json_inspection/AnalyzeNxConfigurationFilesAction.kt
- apps/intellij/src/main/kotlin/dev/nx/console/utils/FindNxConfigurationFiles.kt
Fixes freeze with a following stack trace:
```
"DefaultDispatcher-worker-1" prio=0 tid=0x0 nid=0x0 runnable
java.lang.Thread.State: RUNNABLE
(in native)
at java.base@17.0.10/sun.nio.fs.UnixNativeDispatcher.lstat0(Native Method)
at java.base@17.0.10/sun.nio.fs.UnixNativeDispatcher.lstat(UnixNativeDispatcher.java:308)
at java.base@17.0.10/sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:72)
at java.base@17.0.10/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:52)
at java.base@17.0.10/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
at java.base@17.0.10/java.nio.file.Files.readAttributes(Files.java:1851)
at com.intellij.openapi.util.io.NioFiles.readAttributes(NioFiles.java:187)
at …
```
> fix(intellij): fix freeze

- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
- libs/shared/nx-console-plugins/jest.config.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/index.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/use-generator-defaults-processor.spec.ts
- libs/shared/nx-console-plugins/src/lib/internal-plugins/use-generator-defaults-processor.ts
- libs/shared/nx-console-plugins/tsconfig.json
- libs/shared/nx-console-plugins/tsconfig.spec.json
fixes https://github.com/nrwl/nx-console/issues/1964
> fix(nxls): respect nx.json generator defaults when showing generate ui

- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
- libs/vscode/nvm-tip/src/lib/nvm-tip.ts
- libs/vscode/nx-commands-view/src/lib/nx-commands-provider.ts
- libs/vscode/tasks/src/lib/cli-task-provider.ts
- libs/vscode/utils/src/index.ts
- libs/vscode/utils/src/lib/task-creation-error.ts
This issue was surfaced during https://github.com/nrwl/nx-console/issues/2080.
We now show more information in case something goes wrong during task creation.
> fix(vscode): catch & surface errors during task creation better

- .github/workflows/ci_checks.yml
- apps/generate-ui-v2-e2e/cypress.config.ts
- apps/generate-ui-v2-e2e/project.json
- nx.json
Sets up `@nx/cypress/plugin`:
- with task splitting
- keeping the exact same options for the `e2e` task
- the `watch` configuration becomes the `open-cypress` task
> chore: set up @nx/cypress/plugin

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxReMoveProjectDialog.kt
fixes https://github.com/nrwl/nx-console/issues/2104
before: 
after:
> fix(intellij): set re/move dialog input field width to fill

- apps/intellij/src/main/kotlin/dev/nx/console/generate/NxReMoveProjectDialog.kt
The project text field is focused by default when the re/move project dialog is opened. This improves UX because the user doesn't have to move the focus to the project field manually.
Before:
After:
When the project is prefilled then the destination text box is focused instead:
> feat(intellij): autofocus first empty text field in re/move dialog

- libs/language-server/watcher/src/lib/daemon-watcher.ts
there are versions of nx which contain bugs where the daemon triggers a change even if the contents of `.nx/cache` are changes. This leads to infinite loops in Nx Console, which rebuild the project graph on change.
These are now filtered out - the daemon returns absolute paths here.
> fix(nxls): filter all paths that include a cache folder

- apps/generate-ui-v2/src/utils/generator-schema-utils.spec.ts
I thought it would be nice to have common functions covered by unit tests, to prevent regression bugs in the future.
I have started with normalize schema utils in `apps/generate-ui-v2/src/utils`.
If you think this is a good way to go, I can go and analyze which functions are used the most / are most critical and cover them with tests. I'm also open for suggestions what to look at first.
> chore: add unit tests for generator schema utils

- apps/vscode/package.json
- apps/vscode/src/main.ts
- libs/vscode/lsp-client/src/lib/nxls-client.ts
- libs/vscode/nx-help-and-feedback-view/src/index.ts
- libs/vscode/nx-help-and-feedback-view/src/lib/init-help-and-feedback-view.ts
Before, the new nxls client implementation did not always trigger updates when `Change Workspace` was executed.
Now, it does and the non-nx welcome view in Nx Console is improved:
- The welcome text is useful and actually has the primary action: changing your workspace
- There are links to learn more, following vscode guidelines for welcome views
- The 'generate & run more' view is not included anymore by default since we have the button now
- The 'Help & Feedback' view is included even in non-nx workspaces
Before: 
After:
> fix(vscode): update nxls workspacepath when changing it using the action

- libs/shared/file-system/src/index.ts
- libs/shared/file-system/src/lib/read-directory.ts
- libs/shared/npm/src/lib/npm-dependencies.spec.ts
- libs/shared/npm/src/lib/npm-dependencies.ts
When writing unit tests for [`npmDependencies`](https://github.com/nrwl/nx-console/blob/bfd3c3d4ddb37c8a5fcb6c4b3a3445feb0b3fce5/libs/shared/npm/src/lib/npm-dependencies.ts), I decided to replace `await stat(x)).isDirectory()` with [`directoryExists(x)`](https://github.com/nrwl/nx-console/blob/bfd3c3d4ddb37c8a5fcb6c4b3a3445feb0b3fce5/libs/shared/file-system/src/lib/directory-exists.ts) from `@nx-console/shared/file-system` and added a `readDirectory` function to make it easier to mock those file system operations.
Since the `directoryExists` function already handles thrown exceptions inside, I could refactor the main code by getting rid of the nested try...catch blocks, but then I noticed a strange code path: Before, if `node_modules` was not a directory but an existing file, an empty …
> fix: `npmDependencies` returns dependencies from `.nx/installation/node_modules` if `node_modules` is a file

- apps/vscode/src/nx-schema.json
Use the latest `nx-schema.json`
This patch just pull in the latest changes. Higher level – is there a better way to keep these in sync, or is there a way to tell this plugin to use whatever it finds in the project-level `node_modules`?
> fix: update nx-schema.json to latest

- libs/language-server/watcher/src/lib/daemon-watcher.ts
- libs/language-server/watcher/src/lib/native-watcher.ts
this doesn't fix any specific bug yet - but people have had issues in the past with watchers picking up changes in .nx/cache. So we're going to preemptively ignore the new .nx/workspace-data just to be safe.
> fix(nxls): ignore .nx/workspace-data paths as a precaution

- apps/intellij/src/main/kotlin/dev/nx/console/graph/NxGraphBrowserBase.kt
- apps/intellij/src/main/kotlin/dev/nx/console/run/NxHelpCommandService.kt
- libs/vscode/graph-base/src/lib/handle-graph-interaction-event.ts
This PR updates the handling of `run-help` for both vscode and intellij such that it supports reading `helpCwd` to run the help command. Currently, it is using the project root, which is not always correct, as is the case for `./gradlew`.
> fix: use command cwd when running help command rather than project root

- libs/vscode/generate-ui-webview/src/lib/generate-commands.ts
- libs/vscode/generate-ui-webview/src/lib/init-generate-ui-webview.ts
- libs/vscode/nx-cli-quickpicks/src/lib/select-generator.ts
- libs/vscode/nx-cli-quickpicks/src/lib/select-re-move-generator.ts
- lets user select generator when there is only one generator instead of automatically selecting it (this won't affect the move/remove actions)
- fixes `generatorName` data that is used in generate ui header 
- show proper error when no move / remove generators are available
- simplifies & refactors old code (parts of this were still left over from when there was still a task & generate ui)
> fix(vscode): fix behaviour when only 1 generator is available & refactor old code

- apps/vscode/package.json
- apps/vscode/src/main.ts
- libs/vscode/configuration/src/lib/configuration-keys.ts
This pull request introduces a new configuration option for specifying the Nx workspace path in the VS Code extension. The changes include updates to the configuration schema, new imports and functions to handle the workspace path, and modifications to existing functions to integrate the new setting.
Closes #2268
* [`apps/vscode/package.json`](diffhunk://#diff-ffd752c4d60ebba40a59cc7f9b8cb7b3beeedb5c14a8a8245246bf73846bf247R709-R712): Added a new configuration option `nxConsole.nxWorkspacePath` to specify the relative path to the root directory of the Nx workspace.
* `apps/vscode/src/main.ts`: 
- Added new imports `relative` and `resolve` from the `path` module.
- Integrated `registerSettingsNxWorkspacePathWatcher` in the `activate` function to watch for changes in the new configuration …
> feat(vscode): add nxWorkspacePath configuration option

- apps/intellij/src/main/kotlin/dev/nx/console/telemetry/TelemetryService.kt
this means the logs won't be polluted with these telemetry logs by default
> fix(intellij): make sure telemetry logs are set to trace

- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
- libs/vscode/lsp-client/src/lib/nxls-client.ts
Right now, if a request takes longer and users try to refresh the language server while the request is in flight (actually passed along to the language client, not just in our wrapper), an error will be thrown.
This is potentially very ugly if run from a command and can be avoided. 
With our new state machine architecture, we can simply retry the request since it will automatically wait for the client to be running.
> fix(vscode): retry nxls request if connection is disposed during request

- apps/nxls/src/main.ts
- apps/vscode/src/refresh-workspace.ts
- libs/vscode/lsp-client/src/lib/nxls-client-state-machine.spec.ts
- libs/vscode/lsp-client/src/lib/nxls-client-state-machine.ts
- libs/vscode/lsp-client/src/lib/nxls-client.ts
- feat(nxls): allow nxls to kill itself after 3h of inactivity to prevent background resource usage
- flag behaviour behind initializationOption
> feat(nxls): allow nxls to kill itself after 3h of inactivity to prevent background resource usage

- libs/vscode/project-details/src/lib/project-details-codelens-provider.ts
Currently, actions for opening the PDV aren't super obvious and not many people are doing it. 
This updates the `project.json` codelenses to also have a standalone 'View Project Details' button. 
In the case that no project graph can be computed, it will look the same as before:
> feat(vscode): add standalone project details codelens

- libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts
There's a timing issue that can happen with these commands. Consider the following: 
- User modifies a file (for example breaking `nx.json`)
- Project graph start recalculating in the background
- User right-clicks on Project Tree item (to run a target, for example)
- Project Tree updates, item doesn't exist anymore due to error
- Context menu still exists, user runs command
- Command will be run without existing tree item
> fix(vscode): handle tree items being undefined due to timing issue

- libs/language-server/workspace/src/lib/nx-stop-daemon.ts
- libs/shared/utils/src/index.ts
- libs/shared/utils/src/lib/get-nx-execution-command.ts
- libs/shared/utils/src/lib/package-manager-command.ts
- libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts
- libs/vscode/graph-base/src/lib/nx-graph-server.ts
- libs/vscode/nx-cloud-view/src/lib/init-nx-cloud-view.ts
- libs/vscode/tasks/src/lib/cli-task.ts
- libs/vscode/utils/src/lib/shell-execution.ts
older versions of nx don't `try/catch` when invoking `yarn` or `pnpm`. This means that errors bubble up from nx into nx console. 
When detecting the package manager to run tasks or similar, we catch the error now and default to npm/npx.
> refactor: common getPackageManagerCommand util with try/catch for older nx versions

- libs/language-server/watcher/src/lib/daemon-watcher.ts
Before, the following happened:
- User runs `npx nx daemon --stop`
- Daemon stops
- user checks with `npx nx daemon`
- Daemon is running because nx console restarted it for the watcher in the background
Now we instantly transition to using the native watcher (which is what the daemon uses under the hood itself) if the daemon dies. After a change, the daemon is used again. We could think about changing this as well.
> fix(nxls): use native watcher right away when daemon dies during watch process

- apps/intellij/src/main/kotlin/dev/nx/console/utils/FindNxConfigurationFiles.kt
- **fix(intellij): improve finding Nx configuration files**
- **fix formatting**
> fix(intellij): improve finding Nx configuration files

- libs/language-server/workspace/src/lib/get-nx-workspace-config.ts
- libs/language-server/workspace/src/lib/workspace.ts
saw some error messages in rollbar that were triggered by an undefined `projectGraph` object
> fix(nxls): always provide at least empty project graph object

- libs/vscode/project-details/src/lib/project-details-codelens-provider.ts
Now that `package.json` can contain an `nx` property with information about nx, let's default to that location for the codelens. First fallback is still the `scripts` property and finally the top of the file.
> fix(vscode): show project details codelens above package.json#nx if it exists

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/NxToolWindowPanel.kt
- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectDetailsEditorWithPreview.kt
this fixes an `OverrideOnly` violation as well
> fix(intellij): use refresh service directly and avoid going through actionPerformed

- apps/nxls-e2e/src/document-links/named-input-link-completion-default.test.ts
- libs/language-server/capabilities/code-completion/src/lib/get-completion-items.ts
- libs/language-server/capabilities/document-links/src/lib/get-document-links.ts
- libs/language-server/capabilities/document-links/src/lib/named-input-link.ts
- libs/language-server/capabilities/document-links/src/lib/target-link.ts
- libs/shared/json-schema/src/lib/common-json-schema.ts
- libs/shared/json-schema/src/lib/nx-json-schema.ts
- **fix(nxls): provide dynamic namedInputs autocomplete in nx.json**
- **feat(nxls): add links to namedInputs**
- **add e2e tests**
> feat(nxls): add namedInputs target links & fix namedInputs completion in nx.json

- libs/vscode/typescript-plugin/src/lib/plugin-configuration.ts
we were seeing errors when people don't have `yarn` installed locally. The error was swallowed but we should still fix it.
> fix(vscode): catch yarn --version error in new typescript plugin

- libs/vscode/typescript-plugin/src/lib/plugin-configuration.ts
Catch a potential error when the collected yarn version is not something that can be processed with semver.
> fix(vscode): catch more errors when checking yarn version

- libs/shared/llm-context/src/lib/generator-details.ts
This fixes the getGeneratorSchema for mcps. It handles two things:
* Ensures that we can find aliases like (`@nx/js:lib` instead of `@nx/js:library`)
* And fixes the paths for the schemas to work properly on Windows
> fix: handle aliases and windows paths for getGeneratorSchema

- libs/vscode/migrate/src/lib/commands/migrate-commands.ts
- libs/vscode/migrate/src/lib/migrate-webview.ts
This PR adds a button for user to undo a migration that's already been applied and pending approval.
See: https://www.loom.com/share/97286bdc80ea4538af76a914ef8f0f8b
Also, fixes an existing issue where the `start migrations` commit was never actually done since we did not await the promises from `repository.add` and `repository.commit`.
When a migration is pending approval, the only option is to accept it.
Allow user to undo a migration if they don't want the changes.
Fixes #
> feat(vscode): add undo-migration action when approving current migration

- apps/vscode/project.json
- tools/scripts/copy-to-vscode.js
there were some errors with a packaged nx-console. We now mock one more file in order to get the migrate ui api to work without bundling all the native files.
> fix(vscode): fix wasi loading mock when requiring nx

- apps/vscode/package.json
- libs/shared/nx-cloud/tsconfig.lib.json
- libs/vscode/mcp/src/lib/init-mcp.ts
- libs/vscode/mcp/src/lib/mcp-server.ts
- libs/vscode/migrate-sidebar-webview/tsconfig.webview.json
- libs/vscode/nx-cloud-view/src/cipe-notifications.ts
- libs/vscode/nx-cloud-view/src/cloud-recent-cipe-view.ts
- libs/vscode/utils/src/index.ts
- libs/vscode/utils/src/lib/editor-name-helpers.ts
- libs/vscode/utils/src/lib/is-in-cursor.ts
- libs/vscode/utils/src/lib/mcp-json.ts
- libs/vscode/utils/src/lib/send-message-to-agent.ts
sadly, windsurf doesn't seem to have support for project-level mcp servers right now. This means that we can't reliably register a server for the user as there would be different, competing nx-mcp servers for each workspace and it would be a real mess. 
Right now we'll have to let the users themselves take care of it, hopefully it changes in the future.
> fix(vscode): remove false dichotomy between vscode & cursor. make sure windsurf doesn't get notifications for now

- libs/vscode/typescript-plugin/src/lib/typescript-plugin.ts
we're still seeing this error in rollbar which made me go back and double check. Looks like there was another place in that file where we missed a destructuring statement.
> fix(vscode): fix destructuring from undefined again

- .github/workflows/ci_checks.yml
- apps/intellij/build.gradle.kts
- apps/intellij/src/main/kotlin/dev/nx/console/telemetry/TelemetryService.kt
we don't have to bundle ktor, it's included in the intellij distribution. The version mismatch between what we had and what they had caused some issues. 
Turns out we don't need it anyways, the one `CIO` piece that we're using that they don't include is optional, we can use any other engine for sending basic http requests. 
Tested this out in the GA debug view so it works :)
> fix(intellij): use bundled ktor & verify plugin in CI

- apps/vscode/package.json
- libs/vscode/migrate/src/lib/commands/migrate-commands.ts
- libs/vscode/tasks/src/lib/nx-task-commands.ts
- libs/vscode/tasks/tsconfig.json
- libs/vscode/tasks/tsconfig.lib.json
now that we have the migrate ui, the old command can go... it wasn't really super useful anyways
> fix(vscode): remove legacy migrate command

- libs/vscode/utils/src/lib/mcp-json.ts
- package.json
- yarn.lock
Closes #2504 
Use `jsonc-parser` to parse `mcp.json` which allows comments. This aligns with the VSCode configuration file format described here: https://code.visualstudio.com/docs/languages/json#_json-with-comments
Tested locally to confirm that I can start the nx mcp server with comments in `mcp.json`:
> fix(vscode): parse jsonc mcp.json file

- apps/nx-mcp-e2e/src/workspace_detection.test.ts
- apps/nx-mcp-e2e/src/workspace_path.test.ts
- apps/nx-mcp/src/main.ts
- apps/nx-mcp/tsconfig.app.json
- apps/nx-mcp/tsconfig.json
falling back to the cwd as the workspace path is great but it should check for an nx workspace. Otherwise we will have a lot of nonfunctional tools.
> fix(nx-mcp): workspace tools shouldn't be available if cwd is not an nx workspace

- apps/intellij/src/main/kotlin/dev/nx/console/project_details/ProjectDetailsEditorWithPreview.kt
It can be quite annoying sometimes to always get the preview
> feat(intellij): change default PDV behaviour - show only editor by default instead of split pane

- libs/nx-mcp/nx-mcp-server/src/lib/tools/nx-cloud.ts
- libs/shared/llm-context/src/lib/tool-names.ts
- libs/shared/nx-cloud/src/index.ts
- libs/shared/nx-cloud/src/lib/get-pipeline-execution-details.ts
- libs/shared/nx-cloud/src/lib/get-pipeline-executions-search.ts
- libs/shared/nx-cloud/src/lib/get-run-details.ts
- libs/shared/nx-cloud/src/lib/get-runs-search.ts
- libs/shared/nx-cloud/src/lib/get-task-details.ts
- libs/shared/nx-cloud/src/lib/get-tasks-search.ts
Sketches out tools for:
* Get CIPEs (search)
* Get CIPE details (single entity)
* Get runs (search)
* Get run details (single entity)
* Get tasks (search)
* Get task details (single entity)
Only CIPE tools are exposed at this stage so we can start dogfooding -- follow-ups are on the way for runs, tasks, and likely more.
Will also create a follow-up where we only expose the tools if the Cloud instance that we're trying to connect to can support it.
> feat(nx-mcp): additional tools for Nx Cloud integration

- libs/vscode/nx-cloud-view/src/cipe-notifications.ts
It bothers me that the CI notification says "CI Pipeline Execution has completed" when it actually failed :)
> fix(vscode): update failed CI notification message

- libs/vscode/nx-cloud-fix-webview/src/main.ts
- libs/vscode/nx-cloud-fix-webview/src/nx-cloud-fix-component.ts
- libs/vscode/nx-cloud-view/src/cipe-notifications.ts
- libs/vscode/nx-cloud-view/src/cloud-recent-cipe-view.ts
- libs/vscode/nx-cloud-view/src/cloud-view-state-machine.spec.ts
- libs/vscode/nx-cloud-view/src/init-nx-cloud-view.ts
- libs/vscode/nx-cloud-view/src/nx-cloud-fix-tree-item.ts
- libs/vscode/nx-cloud-view/src/nx-cloud-fix-webview.ts
I refactored the AI fix webview. 
- It's now instantiated at the root of the library and takes care of registering its relevant commands itself.
- It consumes the state machine actor to listen for changes and trigger updates in the UI without destroying everything
- We only pass the cipeId and runGroupId and read from the current state when opening the UI from the notification to make sure that the UI is rendered with the most up-to-date state instead of what was true when the notification popped up. 
- the spinner is a bit slower
> fix(vscode): refactor ai fix webview & automatically update it

- libs/vscode/nx-cloud-fix-webview/src/nx-cloud-fix-component.stories.ts
- libs/vscode/nx-cloud-fix-webview/src/nx-cloud-fix-component.ts
- libs/vscode/nx-cloud-view/src/nx-cloud-fix-webview.ts
This pull request introduces several enhancements and fixes to the `NxCloudFixComponent` and related components, focusing on improving the user interface, handling error states, and refining functionality. Key updates include the addition of a new story for failed fix creation, improved error handling, and UI adjustments for better usability.
* Added logic to handle the "Fix Creation Failed" state in the `getStatusSection` method, displaying a descriptive error message when AI fix creation fails.
* Replaced SVG-based loading icons with `codicon` icons for consistency and reduced complexity. [[1]](diffhunk://#diff-2e091f603b7d3dd8cddbc5ce29e52782255be575b33c191b42b6b1aec14a1312L864-R879) [[2]](diffhunk://#diff-2e091f603b7d3dd8cddbc5ce29e52782255be575b33c191b42b6b1aec14a1312L974-R1010)
* …
> fix(vscode): add 'Fix Creation Failed' state and improve UI elements

- apps/vscode/project.json
- libs/vscode/migrate/src/lib/commands/finish-migration.ts
- libs/vscode/migrate/src/lib/commands/migrate-commands.ts
- libs/vscode/migrate/src/lib/commands/run-migration.ts
- libs/vscode/migrate/src/lib/migrate-webview.ts
This PR works in tandem with https://github.com/nrwl/nx/pull/31626 to enable the new Stop CTA inside of the Migrate UI.
- When we run a migration via the migrate UI it runs as a separate process.
- Ensure that the webview is updated after changes have been made via run migration.
- Add stop command to kill a currently running migration.
- This change also fixes and issue with angular migration. The PR: https://github.com/nrwl/nx-console/pull/2565 was closed in favour of this one.
> feat(migrate): add stop migration functionality and update commands

- libs/vscode/nx-cloud-view/src/cipe-notifications.ts
- libs/vscode/nx-cloud-view/src/cloud-recent-cipe-view.ts
- libs/vscode/nx-cloud-view/src/init-nx-cloud-view.ts
- libs/vscode/nx-cloud-view/src/nx-cloud-fix-webview.ts
This pull request introduces enhancements to the Nx Cloud extension for Visual Studio Code, focusing on AI fix notifications and tree view updates. The changes improve user experience by integrating a status bar indicator for AI fixes, adding badges to the tree view, and ensuring proper cleanup of UI elements when fixes are applied or dismissed.
* Added a `StatusBarItem` to display AI fix suggestions in the status bar, including tooltip and command functionality. The status bar is updated dynamically based on available fixes. (`libs/vscode/nx-cloud-view/src/cipe-notifications.ts`, [[1]](diffhunk://#diff-6858641a2c7901fa6168d454f5672dd8b5f3487c346788ed7691a6f4e435395aL5-R15) [[2]](diffhunk://#diff-6858641a2c7901fa6168d454f5672dd8b5f3487c346788ed7691a6f4e435395aR184-R270)
* Implemented …
> feat(vscode): add status bar item whenever there is a fix available

- libs/vscode/nx-cloud-view/src/cloud-view-state-machine.ts
- libs/vscode/nx-cloud-view/src/init-nx-cloud-view.ts
Reduce Nx Cloud view log noise by removing frequent 'recent-cipe' state logs and adding logs for polling frequency changes.
The original "recent-cipe" state log was outputting every 3 seconds when AI fixes were available, making the logs excessively noisy. This change replaces it with more informative logs that only trigger when the polling frequency actually changes, providing better insight into the state machine's behavior without the constant spam.
> fix(vscode): remove noisy logs from cloud polling

- libs/vscode/mcp/src/lib/mcp-web-server.ts
The `McpWebServer.startSkeletonMcpServer` method in `libs/vscode/mcp/src/lib/mcp-web-server.ts` was updated to handle `EADDRINUSE` errors.
*   When the specified port is already in use, instead of throwing an error, a message is logged to the VS Code output channel via `getOutputChannel().appendLine()`, indicating that this is expected behavior in multi-instance scenarios.
*   A `serverStartupFailed` boolean variable was introduced in `McpWebServer` to track if the server failed to start. This flag is initialized to `false`, set to `true` on startup failure (including `EADDRINUSE`), and set to `false` on successful startup.
*   The `completeMcpServerSetup` method's execution is now conditional on `serverStartupFailed` to prevent SSE transport setup if the server isn't running.
*   The …
> fix(vscode): don't throw error if MCP port is already in use

- apps/intellij/src/main/kotlin/dev/nx/console/cloud/CIPENotificationProcessor.kt
- apps/intellij/src/main/kotlin/dev/nx/console/cloud/CIPENotificationService.kt
- apps/intellij/src/main/kotlin/dev/nx/console/cloud/cloud_fix_ui/NxCloudFixFileImpl.kt
- libs/vscode/nx-cloud-view/src/cipe-notifications.spec.ts
- libs/vscode/nx-cloud-view/src/cipe-notifications.ts
AI fix notifications:
(I forgot to take a new screenshot of the intellij notification, it also has the `#` to mark the branch)
> fix(vscode): rename ai notifications to be stronger & other small fixes

- apps/nx-mcp/jest.config.ts
- apps/nx-mcp/package.json
- apps/nx-mcp/src/main.ts
- apps/nx-mcp/src/yargs-config.spec.ts
- apps/nx-mcp/src/yargs-config.ts
- apps/nx-mcp/tsconfig.app.json
- apps/nx-mcp/tsconfig.json
- apps/nx-mcp/tsconfig.spec.json
SSE is deprecated so while we still support it, we also have to support the new streamable http transport properly.
Now you can control the transport with a `--transport` param, but the `--sse` param still works for backward compat.
Also added some tests around yargs parsing.
> feat(nx-mcp): add streamable http as a transport option & restructure args slightly

- apps/intellij/src/main/kotlin/dev/nx/console/graph/NxGraphBrowserBase.kt
- libs/vscode/graph-base/src/handle-graph-interaction-event.ts
there was a change that required prefixing the taskId with `task-` in some cases so we use the `taskName` instead which is as it always was
> fix: make sure run-task callback from new graph still works

- libs/shared/npm/src/lib/local-nx-utils/package-manager-command.ts
- libs/vscode/mcp/src/lib/agent-rules-manager.ts
We write dynamic workspace info into the agent rules file, like the version & package manager. If these aren't available right now (because the nxls isn't started because of no node_modules, for example), we shouldn't write default values in there.
> fix(vscode): handle no install state better for agent rules manager

- apps/nxls-e2e/src/generators/generator-local-plugin.test.ts
- libs/shared/nx-workspace-info/src/lib/read-collections.ts
When implementing the secondary entry point detection, we also implemented a filter to avoid duplicate entries. 
This was too aggressive since it made a wrong assumption about the structure of these secondary entry points. 
With this fix, everything in the new secondary entry point detection is purely additive so it won't interfere with any other generator detection logic. 
Also, wrapped everything in a try/catch just to be sure.
FIxes https://github.com/nrwl/nx-console/issues/2663
> fix(nxls): remove faulty secondary entry point filtering logic

- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/cloud_tree/CIPESimpleNode.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/cloud_tree/CIPETree.kt
- apps/intellij/src/main/kotlin/dev/nx/console/nx_toolwindow/cloud_tree/CIPETreeStructure.kt
fixes can now handle multiple failed tasks so having them at the task level doesn't really make sense
> fix(intellij): restructure CIPE tree with ai fixes at runGroup level

- apps/nx-mcp-e2e/src/nx-workspace-filter.test.ts
- libs/nx-mcp/nx-mcp-server/src/lib/tools/nx-workspace.test.ts
- libs/nx-mcp/nx-mcp-server/src/lib/tools/nx-workspace.ts
often we don't care about the entire project graph or the project graph is too many tokens to be processed all at once. 
This lets models filter the nx_workspace tool to only what they care about
> feat(nx-mcp): add filtering syntax to nx_workspace tool

- apps/intellij/src/main/kotlin/dev/nx/console/telemetry/TelemetryTypes.kt
- apps/vscode/package.json
- libs/shared/telemetry/src/lib/telemetry-types.ts
- libs/vscode/migrate/src/lib/commands/finish-migration.ts
- libs/vscode/migrate/src/lib/commands/migrate-commands.ts
- libs/vscode/migrate/src/lib/commands/start-migration.ts
- libs/vscode/migrate/src/lib/commands/utils.ts
- libs/vscode/migrate/src/lib/git-extension/view-diff.ts
- libs/vscode/migrate/src/lib/init-migrate.ts
- libs/vscode/migrate/src/lib/migrate-webview.ts
- libs/vscode/migrate/tsconfig.json
- libs/vscode/migrate/tsconfig.lib.json
We've added commands to mirror the main actions that the migrate view sidebar provides:
- start the migration process (we default to custom migration to let user make some choices vs instantly launching into nx migrate in the command line)
- view the package.json diff
- open the migrate UI
These should each only be visible if the migration is in the correct state so we keep track of the state variables via vscode context assignments.
> feat(vscode): improve migrate ui with commands for individual actions

- apps/nx-mcp/README.md
- apps/nx-mcp/src/main.ts
- libs/nx-mcp/nx-mcp-server/src/lib/nx-mcp-server.ts
- libs/nx-mcp/nx-mcp-server/src/lib/resources/nx-cloud-cipe-resources.ts
- libs/nx-mcp/nx-mcp-server/src/lib/tools/nx-cloud.ts
- libs/shared/telemetry/src/lib/telemetry-types.ts
- libs/vscode/mcp/src/lib/data-providers.ts
Expose recent CI Pipeline Executions (CIPEs) as selectable resources in the Nx MCP server.
This PR implements the requested feature to expose recent CIPEs as resources, making them available for selection and detailed viewing in the client. 
- getRecentCIPEs is properly routed through the nxls (in vscode) or directly called from the nx-cloud utils
- We refresh every thirty seconds for now, can hook up with proper client-side handling later
- Outdated CIPEs are removed from the pool of resources
> feat(nx-mcp): expose recent CIPEs as MCP resources

- libs/nx-mcp/nx-mcp-server/src/index.ts
- libs/nx-mcp/nx-mcp-server/src/lib/nx-mcp-server-wrapper.ts
- libs/nx-mcp/nx-mcp-server/src/lib/resources/nx-cloud-cipe-resources.ts
- libs/nx-mcp/nx-mcp-server/src/lib/tools/nx-core.ts
- libs/nx-mcp/nx-mcp-server/src/lib/tools/nx-workspace.ts
- libs/shared/nx-cloud/src/lib/is-nx-cloud-used.ts
- libs/vscode/mcp/src/lib/init-mcp.ts
- libs/vscode/mcp/src/lib/mcp-streamable-web-server.ts
- libs/vscode/utils/src/lib/mcp-json.ts
- make sure agentrulesmanager is only initialized for nx workspaces
- make sure the workspace path passed to nx-mcp is an actual nx workspace
- handle `nx.json` edge case
- make sure ide tools are only registered in nx workspace
> fix(vscode): fix integrated nx-mcp behaviour in non-nx workspace

- apps/vscode/package.json
- libs/vscode/nx-cloud-view/src/cloud-recent-cipe-view.ts
This was a chat participant feature and has been used a grand total of 12 times in the last month.
We can add an equivalent using the MCP but it's apparently not very important right now.
> feat(vscode): remove vscode explain-cipe command

- .github/workflows/publish-vscode.yml
open-vsx.org is definitely the less important marketplace for distributing Nx Console but has outages more often.
This switches the order of the publish so that if it fails, the official marketplace & github release pipelines already went through.
> chore(repo): publish to open-vsx after vscode marketplace & gh are down in case it fails

- .github/workflows/publish-nxls.yml
- apps/nxls/package.json
- nx.json
- package.json
now that we have a new pipeline, we can start releasing the nxls to npm again (--dry-run for now just to see if things work)
> chore(repo): setup nx release for nxls

- apps/vscode/package.json
This should make it easier for folks to see the logs and understand what's wrong with their workspace
> fix(vscode): add logs link to no projects error view

- apps/nx-mcp-e2e/src/nx-project-details-filter.test.ts
- libs/nx-mcp/nx-mcp-server/src/lib/tools/nx-workspace.ts
especially big projects might singlehandedly exceed the 25k token limit for mcp responses that claude code imposes. 
If the agent is just looking for a specific piece of information, it can pass the filter arg now to greatly reduce the amount of json returned from the tool.
> feat(nx-mcp): add filter arg to project_details tool
